### ISSUE TITLE
UnboundLocalError: local variable 'match' referenced before assignment

### ISSUE THREAD

**Issue by yuejun-j-wang** [ablab/IsoQuant#102]
When I run isoquant on my nanopore data, I succeeded on some smaller bam files, but failed on most bam 

2023-07-25 15:17:32,198 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuan
t/issuesconcurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/yuejun/miniconda3/envs/py38/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/yuejun/miniconda3/envs/py38/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/yuejun/miniconda3/envs/py38/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/yuejun/miniconda3/envs/py38/share/isoquant-3.3.0-0/src/dataset_processor.py", line 228, in construct_models_in_parallel
    sqanti_t2t_printer.add_read_info(a)
  File "/home/yuejun/miniconda3/envs/py38/share/isoquant-3.3.0-0/src/assignment_io.py", line 410, in add_read_info
    read_assignment.exon_count(), match.match_classification.name, gene_id, transcript_id,
UnboundLocalError: local variable 'match' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yuejun/miniconda3/envs/py38/bin/isoquant.py", line 698, in <module>
    main(sys.argv[1:])
  File "/home/yuejun/miniconda3/envs/py38/bin/isoquant.py", line 692, in main
    run_pipeline(args)
  File "/home/yuejun/miniconda3/envs/py38/bin/isoquant.py", line 645, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/home/yuejun/miniconda3/envs/py38/share/isoquant-3.3.0-0/src/dataset_processor.py", line 368, in process_all_samples
    self.process_sample(sample)
  File "/home/yuejun/miniconda3/envs/py38/share/isoquant-3.3.0-0/src/dataset_processor.py", line 406, in process_sample
    self.process_assigned_reads(sample, saves_file)
  File "/home/yuejun/miniconda3/envs/py38/share/isoquant-3.3.0-0/src/dataset_processor.py", line 539, in process_assigned_reads
    for read_stat_counter, tsc in results:
  File "/home/yuejun/miniconda3/envs/py38/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/yuejun/miniconda3/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/yuejun/miniconda3/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/yuejun/miniconda3/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
UnboundLocalError: local variable 'match' referenced before assignment

**Comment by yuejun-j-wang** [comment]
[isoquant.log](https://github.com/ablab/IsoQuant/files/12166099/isoquant.log)
[isoquant.error.log](https://github.com/ablab/IsoQuant/files/12166100/isoquant.error.log)

**Comment by andrewprzh** [comment]
Dear @yuejun-j-wang 

This is a known bug in SQANTI-like file output (previously reported in https://github.com/ablab/IsoQuant/issues/96). [This commit](https://github.com/ablab/IsoQuant/commit/c98725d83f4fe2070a4fa01754b5f46f642966cc) fixes it, it will be included in the next release.

Best
Andrey

**Comment by andrewprzh** [comment]
Should be fixed now in version 3.3.1.
