### ISSUE TITLE
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'

### ISSUE THREAD

**Issue by Sourirewang** [ablab/IsoQuant#112]
Hi~
I want to use IsoQuant to quantify the long RNA data of PacBio CCS. 
And my code is  "isoquant.py --reference /data/Wangmeizhen/software/Cogent-master/Amana/WMZ1424/collected/WMZ1424_clustered.hq.fasta.no5merge.collapsed.filtered.rep.fa --fastq /data/Wangmeizhen/Amana/whole_RNA/X101SC22061714-Z01-F004-WMZ1424/WMZ1424_whole.fasta.gz --data_type pacbio_ccs -o WMZ1424/ -t 20"

The alignment process completed but the  quantification failed.
Here is the log file:
2023-09-18 22:48:02,406 - INFO - Running IsoQuant version 3.3.1
2023-09-18 22:48:02,407 - INFO -  === IsoQuant pipeline started === 
2023-09-18 22:48:02,419 - INFO - Indexing reference
2023-09-18 22:48:10,662 - INFO - Aligning /data/Wangmeizhen/Amana/whole_RNA/X101SC22061714-Z01-F004-WMZ1424/WMZ1424_whole.fasta.gz to the reference, alignments will be saved to /data/Wangmeizhen/Amana/expression/ccs/WMZ1424-2/OUT/aux/OUT_WMZ1424_whole_864d45_b646ac.bam
2023-09-18 22:48:10,662 - INFO - Running minimap2 (takes a while)
2023-09-19 03:10:01,992 - INFO - Sorting alignments
2023-09-19 07:45:32,611 - INFO - Indexing alignments
2023-09-19 08:17:34,205 - INFO - Loading reference genome from /data/Wangmeizhen/Amana/whole_RNA/X101SC22061714-Z01-F004-WMZ1424/WMZ1424_clustered.hq.fasta
2023-09-19 08:17:36,160 - INFO - Processing 1 sample
2023-09-19 08:17:36,160 - INFO - Processing sample OUT
2023-09-19 08:17:36,160 - INFO - Sample has 1 BAM file: WMZ1424-2/OUT/aux/OUT_WMZ1424_whole_864d45_b646ac.bam
2023-09-19 08:17:36,161 - INFO - Collecting read alignments
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
Exception ignored in: <function TmpFileAssignmentPrinter.__del__ at 0x7faa8b5f2a60>
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 117, in __del__
    write_short_int(SHORT_TERMINATION_INT, self.dumper)
AttributeError: 'TmpFileAssignmentPrinter' object has no attribute 'dumper'
2023-09-19 08:17:41,036 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesconcurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/dataset_processor.py", line 102, in collect_reads_in_parallel
    tmp_printer = TmpFileAssignmentPrinter(save_file, args)
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 113, in __init__
    AbstractAssignmentPrinter.__init__(self, output_file_name, params)
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/assignment_io.py", line 56, in __init__
    self.output_file = open(self.output_file_name, "w")
FileNotFoundError: [Errno 2] No such file or directory: 'WMZ1424-2/OUT/aux/OUT.save_transcript/0'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/bin/isoquant.py", line 698, in <module>
    main(sys.argv[1:])
  File "/data/Wangmeizhen/.conda/envs/isoquant/bin/isoquant.py", line 692, in main
    run_pipeline(args)
  File "/data/Wangmeizhen/.conda/envs/isoquant/bin/isoquant.py", line 645, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/dataset_processor.py", line 368, in process_all_samples
    self.process_sample(sample)
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/dataset_processor.py", line 392, in process_sample
    self.collect_reads(sample)
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/dataset_processor.py", line 449, in collect_reads
    for storage, read_groups in results:
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: 'WMZ1424-2/OUT/aux/OUT.save_transcript/0'

Are there any resolutions to fix this problem? 
Thanks a lot!

**Comment by andrewprzh** [comment]
Dear @Sourirewang 

I suspect your reference genome has unexpected IDs, i.e. transcript/0.
The slash symbol confuses IsoQuant since it uses FASTA ids in file names.
Could you check or send me the reference, please?

Best
Andrey

**Comment by Sourirewang** [comment]
> Dear @Sourirewang
> 
> I suspect your reference genome has unexpected IDs, i.e. transcript/0. The slash symbol confuses IsoQuant since it uses FASTA ids in file names. Could you check or send me the reference, please?
> 
> Best Andrey

Sorry for the delay. 
I change the "/" to "|" , and it works properly. 
Thanks very musch!

**Comment by andrewprzh** [comment]
@Sourirewang 

Nice to hear that! 

By the way, just in case, IsoQuant expects reference genome to be provided via `--reference` option. I am not sure about the results if the transcriptome is provided (just noticed "transcript" in your FASTA ids).

Best
Andrey

**Comment by Sourirewang** [comment]
> @Sourirewang
> 
> Nice to hear that!
> 
> By the way, just in case, IsoQuant expects reference genome to be provided via `--reference` option. I am not sure about the results if the transcriptome is provided (just noticed "transcript" in your FASTA ids).
> 
> Best Andrey

Yes, you may be right. The program reported an error again:

2023-10-14 01:19:05,155 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesconcurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/dataset_processor.py", line 210, in construct_models_in_parallel
    gene_info, assignment_storage = loader.get_next()
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/dataset_processor.py", line 141, in get_next
    assert self.unpickler.is_gene_info()
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/Wangmeizhen/.conda/envs/isoquant/bin/isoquant.py", line 698, in <module>
    main(sys.argv[1:])
  File "/data/Wangmeizhen/.conda/envs/isoquant/bin/isoquant.py", line 692, in main
    run_pipeline(args)
  File "/data/Wangmeizhen/.conda/envs/isoquant/bin/isoquant.py", line 645, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/dataset_processor.py", line 368, in process_all_samples
    self.process_sample(sample)
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/dataset_processor.py", line 406, in process_sample
    self.process_assigned_reads(sample, saves_file)
  File "/data/Wangmeizhen/.conda/envs/isoquant/share/isoquant-3.3.1-0/src/dataset_processor.py", line 539, in process_assigned_reads
    for read_stat_counter, tsc in results:
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/data/Wangmeizhen/.conda/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
AssertionError

So, Is it not possible for the isoquant to directly quantify transcripts of the full-length transcripts?

**Comment by andrewprzh** [comment]
Dear @Sourirewang 

Could you please send the entire log file? The error looks very suspicious.

>So, Is it not possible for the isoquant to directly quantify transcripts of the full-length transcripts?

Unfortunately yes, IsoQuant is designed to be used with the reference genome only. I can suggest you [NanoSim](https://github.com/bcgsc/NanoSim) quantify module instead.

Best
Andrey

**Comment by andrewprzh** [comment]
Please, reopen if you still encounter this issue in new [version 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0)
