### ISSUE TITLE
 CRITICAL - IsoQuant failed

### ISSUE THREAD

**Issue by francicco** [ablab/IsoQuant#118]
Hi,

I'm getting this error and don't understand why. Any help?
Best
F

```
2023-10-11 22:54:40,067 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesTraceback (most recent call last):
  File "/user/home/tk19812/.conda/envs/isoquant/bin/isoquant.py", line 698, in <module>
    main(sys.argv[1:])
  File "/user/home/tk19812/.conda/envs/isoquant/bin/isoquant.py", line 692, in main
    run_pipeline(args)
  File "/user/home/tk19812/.conda/envs/isoquant/bin/isoquant.py", line 645, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/user/home/tk19812/.conda/envs/isoquant/share/isoquant-3.3.0-0/src/dataset_processor.py", line 368, in process_all_samples
    self.process_sample(sample)
  File "/user/home/tk19812/.conda/envs/isoquant/share/isoquant-3.3.0-0/src/dataset_processor.py", line 392, in process_sample
    self.collect_reads(sample)
  File "/user/home/tk19812/.conda/envs/isoquant/share/isoquant-3.3.0-0/src/dataset_processor.py", line 449, in collect_reads
    for storage, read_groups in results:
  File "/user/home/tk19812/.conda/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/user/home/tk19812/.conda/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/user/home/tk19812/.conda/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/user/home/tk19812/.conda/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by andrewprzh** [comment]
@francicco 

You can try reducing the number of threads - it may save some RAM, I think.

Best
Andrey

**Comment by francicco** [comment]
It looks like IsoQuant loved more memory! :)
Thanks!
F

**Comment by andrewprzh** [comment]
New IsoQuant 3.4 is out, closing this issue for now. Please, re-open if needed.
