### ISSUE TITLE
Error: Coordinates imply a different length than Sequence.seq 

### ISSUE THREAD

**Issue by pclavell** [ablab/IsoQuant#146]
Hello,
I am running IsoQuant on GRCh38.p14 with GENCODE v44 and this error pops up while processing the chromosomes:
raceback (most recent call last):
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/gpfs/projects/bsc83/utils/IsoQuant/src/dataset_processor.py", line 112, in collect_reads_in_parallel
    for gene_info, assignment_storage in alignment_collector.process():
  File "/gpfs/projects/bsc83/utils/IsoQuant/src/alignment_processor.py", line 245, in process
    for res in self.forward_alignments(alignment_storage):
  File "/gpfs/projects/bsc83/utils/IsoQuant/src/alignment_processor.py", line 260, in forward_alignments
    yield self.process_alignments_in_region(current_region, alignment_storage.get_alignments())
  File "/gpfs/projects/bsc83/utils/IsoQuant/src/alignment_processor.py", line 268, in process_alignments_in_region
    gene_info = self.get_gene_info_for_region(current_region)
  File "/gpfs/projects/bsc83/utils/IsoQuant/src/alignment_processor.py", line 462, in get_gene_info_for_region
    gene_info.set_reference_sequence(current_region[0], current_region[1], self.chr_record)
  File "/gpfs/projects/bsc83/utils/IsoQuant/src/gene_info.py", line 623, in set_reference_sequence
    str(chr_record[self.all_read_region_start - 1:self.all_read_region_end + 1])
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/site-packages/pyfaidx/__init__.py", line 789, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/site-packages/pyfaidx/__init__.py", line 139, in __getitem__
    % (self.start, self.end, len(self.seq)))
ValueError: Coordinates (Sequence.start=195063 and Sequence.end=195062) imply a different length than Sequence.seq (len=0). Did you modify Sequence.seq?
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../../../utils/IsoQuant/isoquant.py", line 750, in <module>
    main(sys.argv[1:])
  File "../../../../utils/IsoQuant/isoquant.py", line 744, in main
    run_pipeline(args)
  File "../../../../utils/IsoQuant/isoquant.py", line 697, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/gpfs/projects/bsc83/utils/IsoQuant/src/dataset_processor.py", line 373, in process_all_samples
    self.process_sample(sample)
  File "/gpfs/projects/bsc83/utils/IsoQuant/src/dataset_processor.py", line 397, in process_sample
    self.collect_reads(sample)
  File "/gpfs/projects/bsc83/utils/IsoQuant/src/dataset_processor.py", line 454, in collect_reads
    for storage, read_groups in results:
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
ValueError: Coordinates (Sequence.start=195063 and Sequence.end=195062) imply a different length than Sequence.seq (len=0). Did you modify Sequence.seq?

Thanks a lot

**Comment by jadedavis5** [comment]
Hi I am getting this error too, any updates on when the newest version will be released? 😊

**Comment by andrewprzh** [comment]
@jadedavis5 

If nothing exceptional happens, new release will be out tomorrow.
