### ISSUE TITLE
Unknown (RNA spike-in) reference error when reference appears to be present

### ISSUE THREAD

**Issue by petersbrC** [ablab/IsoQuant#163]
I have also run this after changing the geneID to something unique in the GFF input and had the same result.  

The isoquant traceback is below.

Taken from the genome .fai file to show the ERCC spike in sequence is present in the genome fasta file
ERCC-00033      2014    2228483004      100     101
and here is the matching GFF3 record
ERCC-00033      ERCC    gene    1       2013    .       +       .       ID=ERCC-00033;Note="RNA spike-in"
ERCC-00033      ERCC    mRNA    1       2013    .       +       .       ID=ERCC-00033.m1;Parent=ERCC-00033;Note="RNA spike-in"
ERCC-00033      ERCC    exon    1       2013    .       +       .       ID=ERCC-00033.m1.e1;Parent=ERCC-00033.m1

Traceback:

concurrent.futures.process._RemoteTraceback: 
   3866 """
   3867 Traceback (most recent call last):
   3868   File "python3.8/concurrent/futures/process.py", line 239, in _process_worker
   3869     r = call_item.fn(*call_item.args, **call_item.kwargs)
   3870   File "python3.8/concurrent/futures/process.py", line 198, in _process_chunk
   3871     return [fn(*args) for args in chunk]
   3872   File "python3.8/concurrent/futures/process.py", line 198, in <listcomp>
   3873     return [fn(*args) for args in chunk]
   3874   File "isoquant-3.3.1-0/src/dataset_processor.py", line 109, in collect_reads_in_parallel
   3875     AlignmentCollector(chr_id, bam_file_pairs, args, gffutils_db, current_chr_record, read_grouper)
   3876   File "isoquant-3.3.1-0/src/alignment_processor.py", line 228, in __init__
   3877     self.bam_pairs[0][0].get_reference_length(self.chr_id),
   3878   File "pysam/libcalignmentfile.pyx", line 1914, in pysam.libcalignmentfile.AlignmentFile.get_reference_length
   3879   File "pysam/libcalignmentfile.pyx", line 507, in pysam.libcalignmentfile.AlignmentHeader.get_reference_length
   3880 KeyError: 'unknown reference ERCC-00033'
   3881 """
   3882 
   3883 The above exception was the direct cause of the following exception:
   3884 
   3885 Traceback (most recent call last):
   3886   File "isoquant.py", line 698, in <module>
   3887     main(sys.argv[1:])
   3888   File "isoquant.py", line 692, in main
   3889     run_pipeline(args)
   3890   File "isoquant.py", line 645, in run_pipeline
   3891     dataset_processor.process_all_samples(args.input_data)
   3892   File "isoquant-3.3.1-0/src/dataset_processor.py", line 368, in process_all_samples
   3893     self.process_sample(sample)
   3894   File "isoquant-3.3.1-0/src/dataset_processor.py", line 392, in process_sample
   3895     self.collect_reads(sample)
   3896   File "isoquant-3.3.1-0/src/dataset_processor.py", line 449, in collect_reads
   3897     for storage, read_groups in results:
   3898   File "python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
   3899     for element in iterable:
   3900   File "python3.8/concurrent/futures/_base.py", line 619, in result_iterator
   3901     yield fs.pop().result()
   3902   File "python3.8/concurrent/futures/_base.py", line 437, in result
   3903     return self.__get_result()
   3904   File "python3.8/concurrent/futures/_base.py", line 389, in __get_result
   3905     raise self._exception
   3906 KeyError: 'unknown reference ERCC-00033'
   3907

_Originally posted by @petersbrC in https://github.com/ablab/IsoQuant/issues/155#issuecomment-1979013458_

**Comment by petersbrC** [comment]
Sorry, log is slow as I have to anonymize it before I can post.

Could this be related to having zero alignments in a sample to the ERCC spike in that I've called a reference sequence in my setup?  Could I work around this by creating a fake ERCC reference with all the spike-in sequences concatenated and adjust the gff3 file accordingly.


```
 for b in *.desalt.bam; do echo $b; samtools view $b | grep -c ERCC-00033; done
1.desalt.bam
4
2.desalt.bam
10
3.desalt.bam
3
4.desalt.bam
3
5.desalt.bam
6
6.desalt.bam
0
7.desalt.bam
2
8.desalt.bam
6
9.desalt.bam
4
10.desalt.bam
9
11.desalt.bam
3
12.desalt.bam
1
```

**Comment by petersbrC** [comment]
This turned out to be a stupid mistake.  I was preparing inputs and kicking IsoQuant off from a Jupyter notebook and the bam list file failed to overwrite and pointed to bam files that did not include the spike in references.

My IsoQuant log files are clogged with "has no exons" warnings which buried the call info.  When trying to find the bam that might be throwing the error I found it to be different than what I thought IsoQuant was running one.

My apologies for taking up your time.  Really love IsoQuant, pretty fabulous app.  Not only in what it does but also in ease of getting it running.  Very polished in comparison to many bioinformatics apps and that is appreciated!
