### ISSUE TITLE
Error when running test following installation

### ISSUE THREAD

**Issue by TBrownmiller** [ablab/IsoQuant#169]
Hello, I followed the installation instructions and ran the test as recommended and I am receiving this error:

=== Running in test mode ===
Any other option is ignored
2024-03-19 09:00:48,585 - INFO - Running IsoQuant version 3.3.1
2024-03-19 09:00:48,589 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesTraceback (most recent call last):
  File "/vf/users/brownmillertb/conda/envs/isoquant/bin/isoquant.py", line 750, in <module>
    main(sys.argv[1:])
  File "/vf/users/brownmillertb/conda/envs/isoquant/bin/isoquant.py", line 739, in main
    args, parser = parse_args(args)
  File "/vf/users/brownmillertb/conda/envs/isoquant/bin/isoquant.py", line 225, in parse_args
    args = parser.parse_args(cmd_args, namespace)
  File "/vf/users/brownmillertb/conda/envs/isoquant/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/vf/users/brownmillertb/conda/envs/isoquant/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/vf/users/brownmillertb/conda/envs/isoquant/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/vf/users/brownmillertb/conda/envs/isoquant/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/vf/users/brownmillertb/conda/envs/isoquant/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/vf/users/brownmillertb/conda/envs/isoquant/bin/isoquant.py", line 721, in __call__
    main(options)
  File "/vf/users/brownmillertb/conda/envs/isoquant/bin/isoquant.py", line 741, in main
    args = check_and_load_args(args, parser)
  File "/vf/users/brownmillertb/conda/envs/isoquant/bin/isoquant.py", line 294, in check_and_load_args
    if not check_input_params(args):
  File "/vf/users/brownmillertb/conda/envs/isoquant/bin/isoquant.py", line 389, in check_input_params
    check_input_files(args)
  File "/vf/users/brownmillertb/conda/envs/isoquant/bin/isoquant.py", line 411, in check_input_files
    if sample.illumina_bam is not None:
AttributeError: 'SampleData' object has no attribute 'illumina_bam'

**Comment by andrewprzh** [comment]
@TBrownmiller 

Looks odd, how did you install IsoQuant, via conda?

Best
Andrey

**Comment by TBrownmiller** [comment]
Yes, I used "conda install -c bioconda isoquant" as listed under the Installation section of the README

Thanks
Tayvia

**Comment by andrewprzh** [comment]
@TBrownmiller 

Clearly is something wrong with you installation, because version 3.3.1 available on conda does not contain this code related to `illumina_bam` variable.

Could you try to installing IsoQuant to a new empty environment or download it from GitHub release?

Best
Andrey

**Comment by andrewprzh** [comment]
New version 3.4 is released. Please, re-open issue if the problem is still there.
