### ISSUE TITLE
issue with reference file

### ISSUE THREAD

**Issue by janeshen91** [ablab/IsoQuant#179]
Hello I ran the following command

str="20240411_1157_X1_FAX08446_1caf24e2"
docker run -v /vaxart-batch-input/:/input \
-v /vaxart-batch-output/$str:/output quay.io/biocontainers/isoquant:3.3.1--hdfd78af_0 isoquant.py \
--bam /output/samtools/reference/${str}_sorted.bam \
--reference /output/reference/reference.fa \
--data_type nanopore \
-o /output/isoquant --report_novel_unspliced

and encountered the output 

2024-04-30 22:59:58,231 - INFO - Running IsoQuant version 3.3.1
2024-04-30 22:59:58,232 - WARNING - Output folder already exists, some files may be overwritten.
2024-04-30 22:59:58,327 - INFO - Novel unspliced transcripts will not be reported, set --report_novel_unspliced true to discover them
2024-04-30 22:59:58,327 - INFO -  === IsoQuant pipeline started === 
2024-04-30 22:59:58,327 - INFO - Loading reference genome from /output/reference/reference.fa
2024-04-30 22:59:58,354 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesTraceback (most recent call last):
  File "/usr/local/bin/isoquant.py", line 698, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/isoquant.py", line 692, in main
    run_pipeline(args)
  File "/usr/local/bin/isoquant.py", line 644, in run_pipeline
    dataset_processor = DatasetProcessor(args)
  File "/usr/local/share/isoquant-3.3.1-0/src/dataset_processor.py", line 339, in __init__
    os.symlink(self.args.reference, symlink_name)
OSError: [Errno 524] Unknown error 524: '/output/reference/reference.fa' -> '/output/isoquant/reference.fa'

As it directs me to submit this issue to github, can you please help?  Is there something wrong with symoblically linking the reference file?

Thanks
Jane

**Comment by andrewprzh** [comment]
Dear @janeshen91 

>Is there something wrong with symoblically linking the reference file?

I seems so. However, the log doesn't give much information besides "Unknown error".
I see you use docker, right? Could you check whether symlinks work there just as usual?

IsoQuant does make a symlink to the reference file, since pyfaidx lib needs to make an index and by default it builds the index in the same folder as the FASTA files, which might be read-only. 
It seems that it's possible to avoid symlinking and build an index in another location. I'll try to fix this workaround in the next release.

Best
Andrey

**Comment by janeshen91** [comment]
Thanks Andrey. It does seem like there is a problem with my server not allowing me to create symlinks as usual. I'm trying to fix that, but is there any other work around right now? I've tried copying the reference file to the isoquant output folder but it didn't seem to solve the problem.

**Comment by andrewprzh** [comment]
@janeshen91 

1. First workaround is to run `samtools faidx /output/reference/reference.fa`, which will create a .fai index right near the reference genome. In this case IsoQuant won't create symlinks and use existing index.

2. Apply this commit: https://github.com/ablab/IsoQuant/commit/dbd6074e040b903dc8b96ab8e00cb97e980fb101

Best
Andrey

**Comment by janeshen91** [comment]
I'll try those, thanks Andrey!

**Comment by andrewprzh** [comment]
There are no symbolic links in the new version [IsoQuant 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0). So should work fine.

**Comment by janeshen91** [comment]
Thanks Andrey!
