### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by simoncchu** [ablab/IsoQuant#20]
I met this issue while I am trying on a plant genome:
```
IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issues
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/miniconda3/envs/isoquant/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/miniconda3/envs/isoquant/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/miniconda3/envs/isoquant/share/isoquant-1.2.1-1/src/dataset_processor.py", line 123, in process_in_parallel
    assignment_storage = alignment_processor.process()
  File "/home/miniconda3/envs/isoquant/share/isoquant-1.2.1-1/src/alignment_processor.py", line 52, in process
    self.process_single_file(b)
  File "/home/miniconda3/envs/isoquant/share/isoquant-1.2.1-1/src/alignment_processor.py", line 96, in process_single_file
    read_assignment = self.assigner.assign_to_isoform(read_id, combined_profile)
  File "/home/miniconda3/envs/isoquant/share/isoquant-1.2.1-1/src/long_read_assigner.py", line 388, in assign_to_isoform
    gene_region = (self.gene_info.split_exon_profiles.features[0][0],
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/isoquant/bin/isoquant.py", line 472, in <module>
    main(sys.argv[1:])
  File "/home/miniconda3/envs/isoquant/bin/isoquant.py", line 465, in main
    run_pipeline(args)
  File "/home/miniconda3/envs/isoquant/bin/isoquant.py", line 446, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/home/miniconda3/envs/isoquant/share/isoquant-1.2.1-1/src/dataset_processor.py", line 156, in process_all_samples
    self.process_sample(sample)
  File "/home/miniconda3/envs/isoquant/share/isoquant-1.2.1-1/src/dataset_processor.py", line 175, in process_sample
    pool.starmap(process_in_parallel, [(sample, chr_id, c, self.args, self.read_grouper,
  File "/home/miniconda3/envs/isoquant/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/miniconda3/envs/isoquant/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range
```

Also, before this there are some warnings like:
```
2021-05-10 04:20:03,293 - INFO - Processing chromosome Chr06
2021-05-10 04:20:03,295 - WARNING - Gene EVM0041976 has no exons / transcripts, check your input annotation
2021-05-10 04:20:03,296 - WARNING - Gene EVM0000049 has no exons / transcripts, check your input annotation
2021-05-10 04:20:03,298 - WARNING - Gene EVM0020463 has no exons / transcripts, check your input annotation
2021-05-10 04:20:03,298 - WARNING - Gene EVM0005505 has no exons / transcripts, check your input annotation
2021-05-10 04:20:03,300 - WARNING - Gene EVM0021688 has no exons / transcripts, check your input annotation
2021-05-10 04:20:03,495 - INFO - Processing chromosome Chr15
2021-05-10 04:20:03,498 - WARNING - Gene EVM0043300 has no exons / transcripts, check your input annotation

```
and if I search "EVM0041976" in my `gff3` file I got:
```
Chr06	EVM	gene	6016	12455	.	+	.	ID=EVM0041976;
Chr06	EVM	mRNA	6016	12455	.	+	.	ID=EVM0041976.1;Parent=EVM0041976;
Chr06	EVM	five_prime_UTR	6016	6251	.	+	.	Parent=EVM0041976.1;
Chr06	EVM	five_prime_UTR	6697	6757	.	+	.	Parent=EVM0041976.1;
Chr06	EVM	exon	6016	6251	.	+	.	Parent=EVM0041976.1;
Chr06	EVM	exon	6697	7156	.	+	.	Parent=EVM0041976.1;
Chr06	EVM	exon	7956	8075	.	+	.	Parent=EVM0041976.1;
Chr06	EVM	exon	8241	8294	.	+	.	Parent=EVM0041976.1;
Chr06	EVM	exon	9976	10139	.	+	.	Parent=EVM0041976.1;
Chr06	EVM	exon	10832	11008	.	+	.	Parent=EVM0041976.1;
Chr06	EVM	exon	12153	12455	.	+	.	Parent=EVM0041976.1;
Chr06	EVM	CDS	6758	7156	.	+	0	Parent=EVM0041976.1;
Chr06	EVM	CDS	7956	8075	.	+	0	Parent=EVM0041976.1;
Chr06	EVM	CDS	8241	8294	.	+	0	Parent=EVM0041976.1;
Chr06	EVM	CDS	9976	10139	.	+	0	Parent=EVM0041976.1;
Chr06	EVM	CDS	10832	11008	.	+	2	Parent=EVM0041976.1;
Chr06	EVM	CDS	12153	12363	.	+	2	Parent=EVM0041976.1;
Chr06	EVM	three_prime_UTR	12364	12455	.	+	.	Parent=EVM0041976.1;

```

This is the command I used:
```
isoquant.py -g EVM.final.all.transcripts.gene.gff3 --bam sorted.bam --data_type pacbio_ccs -o ./rslts/
```

Any suggestions? Thank you a lot.

**Comment by andrewprzh** [comment]
Hi!

Annotation files are processed with gffutils lib, so my guess is that in doesn't see gene_id/transcript_id for these exons.
Could you share some data so I can verify the problem?
For data sharing you can contact me directly via email in the profile.

Best
Andrey

**Comment by simoncchu** [comment]
Updated version solved the issue. Thank you for all the help!

**Comment by andrewprzh** [comment]
Thank you for your feedback!

Fixed in https://github.com/ablab/IsoQuant/releases/tag/v1.2.2, available from bioconda as well.

**Comment by zhou-ran** [comment]
Hi,
I meet this error in IsoQuant 2.2.1 for processing gtf file download from https://ftp.ensembl.org/pub/release-101/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.101.gtf.gz

```
IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issues
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/NAS/zym/env/miniconda3/envs/isoquant/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/NAS/zym/env/miniconda3/envs/isoquant/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 129, in assign_reads_in_parallel
    gene_info = GeneInfo(g, gffutils_db, args.delta)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/gene_info.py", line 132, in __init__
    self.set_junction_profiles(self.all_isoforms_introns, self.all_isoforms_exons)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/gene_info.py", line 442, in set_junction_profiles
    transcript_region = self.transcript_region(t.id)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/gene_info.py", line 488, in transcript_region
    return (self.transcript_start(transcript_id), self.transcript_end(transcript_id))
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/gene_info.py", line 482, in transcript_start
    return self.all_isoforms_exons[transcript_id][0][0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/NAS/zym/env/miniconda3/envs/isoquant/bin/isoquant.py", line 486, in <module>
    main(sys.argv[1:])
  File "/NAS/zym/env/miniconda3/envs/isoquant/bin/isoquant.py", line 480, in main
    run_pipeline(args)
  File "/NAS/zym/env/miniconda3/envs/isoquant/bin/isoquant.py", line 466, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 265, in process_all_samples
    self.process_sample(sample)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 279, in process_sample
    self.assign_reads(sample)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 303, in assign_reads
    results = pool.starmap(assign_reads_in_parallel, [(sample, chr_id, c, self.args, self.read_grouper,
  File "/NAS/zym/env/miniconda3/envs/isoquant/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/NAS/zym/env/miniconda3/envs/isoquant/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range
```

Ran

**Comment by andrewprzh** [comment]
Dear Ran

This seems like a different issue from the first look. Could you please submit a new issue and attach a full isoquant.log file?

Best
Andrey
