### ISSUE TITLE
isoquant.py --test issue

### ISSUE THREAD

**Issue by sophielemoine** [ablab/IsoQuant#215]
Dear developper,
I want to use the last version of isoquant (it's time to wobe forward because I currently use version 3.3.0) but I cannot go too far. The test does not succeed.
Here is the message I get : 

2024-07-16 12:09:43,204 - INFO - Running IsoQuant version 3.4.2
2024-07-16 12:09:43,213 - INFO - Novel unspliced transcripts will not be reported, set --report_novel_unspliced true to discover them
2024-07-16 12:09:43,213 - INFO -  === IsoQuant pipeline started === 
2024-07-16 12:09:43,213 - INFO - gffutils version: 0.10.1
2024-07-16 12:09:43,213 - INFO - pysam version: 0.17.0
2024-07-16 12:09:43,214 - INFO - pyfaidx version: 0.0.0
2024-07-16 12:09:43,216 - INFO - Checking input gene annotation
2024-07-16 12:09:43,229 - INFO - Gene annotation seems to be correct
2024-07-16 12:09:43,229 - INFO - Converting gene annotation file to .db format (takes a while)...
2024-07-16 12:09:43,375 - INFO - Gene database written to /data/isoquant_test/chr9.4M.gtf.db
2024-07-16 12:09:43,375 - INFO - Provide this database next time to avoid excessive conversion
2024-07-16 12:09:43,378 - INFO - Indexing reference
2024-07-16 12:09:43,592 - INFO - Converting gene annotation file /data/isoquant_test/chr9.4M.gtf.db to .bed format
2024-07-16 12:09:43,651 - INFO - Gene database BED written to isoquant_test/chr9.4M.gtf.bed
2024-07-16 12:09:43,655 - INFO - Aligning /usr/local/IsoQuant/tests/simple_data/chr9.4M.ont.sim.fq.gz to the reference, alignments will be saved to /data/isoquant_test/TEST_DATA/aux/TEST_DATA_chr9.4M.ont.sim_c68282_b13147_dee856.bam
2024-07-16 12:09:43,659 - INFO - Running minimap2 version 2.24-r1122 (takes a while)
2024-07-16 12:09:46,598 - INFO - Sorting alignments
2024-07-16 12:09:46,681 - INFO - Indexing alignments
2024-07-16 12:09:46,702 - INFO - Loading gene database from /data/isoquant_test/chr9.4M.gtf.db
2024-07-16 12:09:46,718 - INFO - Loading reference genome from /usr/local/IsoQuant/tests/simple_data/chr9.4M.fa.gz
2024-07-16 12:09:46,720 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesTraceback (most recent call last):
  File "/usr/local/IsoQuant/isoquant.py", line 808, in <module>
    main(sys.argv[1:])
  File "/usr/local/IsoQuant/isoquant.py", line 797, in main
    args, parser = parse_args(args)
  File "/usr/local/IsoQuant/isoquant.py", line 254, in parse_args
    args = parser.parse_args(cmd_args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 1845, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 1878, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 2091, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.10/argparse.py", line 2031, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.10/argparse.py", line 1955, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/IsoQuant/isoquant.py", line 779, in __call__
    main(options)
  File "/usr/local/IsoQuant/isoquant.py", line 802, in main
    run_pipeline(args)
  File "/usr/local/IsoQuant/isoquant.py", line 754, in run_pipeline
    dataset_processor = DatasetProcessor(args)
  File "/usr/local/IsoQuant/src/dataset_processor.py", line 429, in __init__
    self.reference_record_dict = Fasta(self.args.reference, indexname=args.fai_file_name)
TypeError: Fasta.__init__() got an unexpected keyword argument 'indexname'

Thanks a lot for your help.

**Comment by andrewprzh** [comment]
@sophielemoine 

There is something wrong with your pyfaidx installation
`2024-07-16 12:09:43,214 - INFO - pyfaidx version: 0.0.0`

Please, update it to version 0.7 or higher.

Best
Andrey

**Comment by sophielemoine** [comment]
Yes I noticed that weird stuff.
I used python3-pyfaidx (0.6.4-1) from ubuntu 22.04.
Thanks for your answer, I am going to switch my dockerfile to 24.04.

**Comment by sophielemoine** [comment]
And it's working !
