### ISSUE TITLE
Visualize.py with linear output

### ISSUE THREAD

**Issue by ljwharbers** [ablab/IsoQuant#241]
Hi,

Just wanted to bring to the attention here that visualize.py currently only works for the 'standard' wide output that is the default. On data that is run with `--counts_format linear`, the tool will crash with the following error (whiel trying to read in genes).
```
$ visualize.py . --gene_list ../genes.txt --counts

/some/path/isoquant-3.6.0-0/src/file_utils.py:25: SyntaxWarning: invalid escape sequence '\d'
  file_names.sort(key=lambda s: [int(t) if t.isdigit() else t.lower() for t in re.split('(\d+)', s)])
File ./OUT/OUT.read_assignments.tsv.gz was decompressed to ./OUT/OUT.read_assignments.tsv.
Traceback (most recent call last):
  File "/some/path/visualize.py", line 184, in <module>
    main()
  File "/some/path/visualize.py", line 95, in main
    updated_gene_dict = dictionary_builder.update_gene_dict(gene_dict, gene_file)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/path/isoquant-3.6.0-0/src/post_process.py", line 464, in update_gene_dict
    header = next(reader)
             ^^^^^^^^^^^^
StopIteration
```

Hopefully you would consider also making it compatible with the linear output format. If not, it would be good to specify in the documentation that only the 'wide' output is supported and check for empty files so the error message would be clearer. 

Thanks again for the great tool!

Best,
Luuk

**Comment by andrewprzh** [comment]
Dear @ljwharbers 

Yes, visualizer was not designed to work with the linear format, and the option was introduced later without properly adapting `visualize.py`. Thank you for bringing our attention - we will improve this functionality.

Best
Andrey

**Comment by andrewprzh** [comment]
Fixed in master branch now.
