### ISSUE TITLE
Handling viral gff files

### ISSUE THREAD

**Issue by rebeelouise** [ablab/IsoQuant#263]
Hi!

I am trying to use isoquant within the polyTailor tool. 

I am looking at viral sequences... 

Isoquant does not like the viral gff files and throws the below error. 

````
2024-12-02 19:46:39,045 - INFO -  === IsoQuant pipeline started === 
2024-12-02 19:46:39,046 - INFO - gffutils version: 0.13
2024-12-02 19:46:39,046 - INFO - pysam version: 0.22.1
2024-12-02 19:46:39,046 - INFO - pyfaidx version: 0.8.1.3
2024-12-02 19:46:39,048 - INFO - Checking input gene annotation
2024-12-02 19:46:39,050 - INFO - Gene annotation seems to be correct
2024-12-02 19:46:39,050 - INFO - Converting gene annotation file to .db format (takes a while)...
2024-12-02 19:46:39,077 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesTraceback (most recent call last):
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/lib/python3.10/site-packages/gffutils/create.py", line 622, in _populate_from_lines
    self._insert(f, c)
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/lib/python3.10/site-packages/gffutils/create.py", line 566, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.IntegrityError: UNIQUE constraint failed: features.id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/bin/isoquant.py", line 819, in <module>
    main(sys.argv[1:])
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/bin/isoquant.py", line 813, in main
    run_pipeline(args)
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/bin/isoquant.py", line 749, in run_pipeline
    args.genedb = convert_gtf_to_db(args)
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/share/isoquant-3.6.2-0/src/gtf2db.py", line 144, in convert_gtf_to_db
    gtf_filename, genedb_filename = convert_db(gtf_filename, genedb_filename, gtf2db, args)
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/share/isoquant-3.6.2-0/src/gtf2db.py", line 360, in convert_db
    convert_fn(gtf_filename, genedb_filename, args.complete_genedb, args.gtf_check)
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/share/isoquant-3.6.2-0/src/gtf2db.py", line 133, in gtf2db
    gffutils.create_db(gtf, db, force=True, keep_order=True, merge_strategy='error',
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/lib/python3.10/site-packages/gffutils/create.py", line 1401, in create_db
    c.create()
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/lib/python3.10/site-packages/gffutils/create.py", line 543, in create
    self._populate_from_lines(self.iterator)
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/lib/python3.10/site-packages/gffutils/create.py", line 624, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/home/van_hohenheim/miniforge3/envs/polyTailor/lib/python3.10/site-packages/gffutils/create.py", line 257, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID cds-NP_073549.1
`

```
Have any virologists got any hacks? Or do the writers of this tool know how I can get around this sensibly??

For another reference I am getting the following messages:

```
`2024-12-02 19:14:12,804 - INFO -  === IsoQuant pipeline started === 
2024-12-02 19:14:12,804 - INFO - gffutils version: 0.13
2024-12-02 19:14:12,804 - INFO - pysam version: 0.22.1
2024-12-02 19:14:12,804 - INFO - pyfaidx version: 0.8.1.3
2024-12-02 19:14:12,807 - INFO - Gene annotation file found. Using /mnt/g/rebee/projects/nano3p_seq/polyTailor/isoquant/MNV.db
2024-12-02 19:14:12,807 - INFO - Loading gene database from /mnt/g/rebee/projects/nano3p_seq/polyTailor/isoquant/MNV.db
2024-12-02 19:14:12,818 - INFO - Loading reference genome from /mnt/g/rebee/projects/nano3p_seq/references/MNVNoV-400.reference.fasta
2024-12-02 19:14:12,822 - INFO - Processing 1 experiment
2024-12-02 19:14:12,822 - INFO - Processing experiment OUT
2024-12-02 19:14:12,822 - INFO - Experiment has 1 BAM file: align/algs.bam
2024-12-02 19:14:12,824 - INFO - Collecting read alignments
2024-12-02 19:14:12,864 - INFO - Processing chromosome NC_008311.1
2024-12-02 19:14:13,604 - WARNING - Gene gene-NoVGV_gp1 has no exons / transcripts, check your input annotation
2024-12-02 19:14:13,604 - WARNING - Genes gene-NoVGV_gp1, gene-NoVGV_gp2, gene-NoVGV_gp4, gene-NoVGV_gp3 have no exons, check you GTF file
2024-12-02 19:14:16,211 - INFO - Finished processing chromosome NC_008311.1
2024-12-02 19:14:16,244 - INFO - Counting multimapped reads
2024-12-02 19:14:16,244 - INFO - Loading read assignments from isoquant/OUT/aux/OUT.save_NC_008311.1
2024-12-02 19:14:16,539 - INFO - Resolving multimappers
2024-12-02 19:14:16,542 - INFO - Multimappers resolved
2024-12-02 19:14:16,546 - INFO - Alignments collected, overall alignment statistics:
2024-12-02 19:14:16,546 - INFO - primary: 22357
2024-12-02 19:14:16,547 - INFO - secondary: 1
2024-12-02 19:14:16,547 - INFO - supplementary: 133
2024-12-02 19:14:16,547 - INFO - unaligned: 2082329
2024-12-02 19:14:16,551 - INFO - Finishing read assignment, total assignments 22357, polyA percentage 53.5
2024-12-02 19:14:16,552 - INFO - Read assignments files saved to isoquant/OUT/aux/OUT.save*. 
2024-12-02 19:14:16,552 - INFO - To keep these intermediate files for debug purposes use --keep_tmp flag
2024-12-02 19:14:16,554 - INFO - Total assignments used for analysis: 22357, polyA tail detected in 11960 (53.5%)
2024-12-02 19:14:16,554 - INFO - Processing assigned reads OUT
2024-12-02 19:14:16,554 - INFO - Transcript models construction is turned on
2024-12-02 19:14:16,560 - INFO - Transcript construction options:
2024-12-02 19:14:16,560 - INFO -   Novel monoexonic transcripts will be reported: yes
2024-12-02 19:14:16,561 - INFO -   PolyA tails are required for multi-exon transcripts to be reported: no
2024-12-02 19:14:16,561 - INFO -   PolyA tails are required for 2-exon transcripts to be reported: yes
2024-12-02 19:14:16,561 - INFO -   PolyA tails are required for known monoexon transcripts to be reported: yes
2024-12-02 19:14:16,561 - INFO -   PolyA tails are required for novel monoexon transcripts to be reported: yes
2024-12-02 19:14:16,561 - INFO -   Splice site reporting level: only_stranded
2024-12-02 19:14:16,583 - INFO - Processing chromosome NC_008311.1
2024-12-02 19:14:16,608 - INFO - Loading read assignments from isoquant/OUT/aux/OUT.save_NC_008311.1
2024-12-02 19:14:16,616 - WARNING - Gene gene-NoVGV_gp1 has no exons / transcripts, check your input annotation
2024-12-02 19:14:18,062 - WARNING - Gene gene-NoVGV_gp1 has no exons / transcripts, check your input annotation
2024-12-02 19:14:18,062 - WARNING - Genes gene-NoVGV_gp1, gene-NoVGV_gp2, gene-NoVGV_gp4, gene-NoVGV_gp3 have no exons, check you GTF file
2024-12-02 19:14:18,084 - INFO - Finished processing chromosome NC_008311.1
2024-12-02 19:14:18,188 - INFO - Transcript model file isoquant/OUT/OUT.transcript_models.gtf
2024-12-02 19:14:18,192 - INFO - Extended annotation is saved to isoquant/OUT/OUT.extended_annotation.gtf
2024-12-02 19:14:18,192 - INFO - Transcript model statistics
2024-12-02 19:14:18,192 - INFO - novel_not_in_catalog: 3
2024-12-02 19:14:18,413 - INFO - Gene counts are stored in isoquant/OUT/OUT.gene_counts.tsv
2024-12-02 19:14:18,414 - INFO - Transcript counts are stored in isoquant/OUT/OUT.transcript_counts.tsv
2024-12-02 19:14:18,414 - INFO - Read assignments are stored in isoquant/OUT/OUT.read_assignments.tsv.gz
2024-12-02 19:14:18,414 - INFO - Read assignment statistics
2024-12-02 19:14:18,415 - INFO - intergenic: 22357
2024-12-02 19:14:18,437 - INFO - Processed experiment OUT
2024-12-02 19:14:18,437 - INFO - Processed 1 experiment
2024-12-02 19:14:18,437 - INFO -  === IsoQuant pipeline finished === 
`
```

**Comment by andrewprzh** [comment]
Dear @rebeelouise 

In the first message gffutils detect identical IDs in your GFF:
`ValueError: Duplicate ID cds-NP_073549.1`

Duplicating IDs, in fact, violate GFF/GTF format in general (even for features of different type, e.g. gene and CDS may not have the same ID), so other tools might not like it as well. I suggest to change duplicating IDs.

Second message complains about genes not having transcript / exon children records. IsoQuant is primarily designed for eukaryotes and expects each gene to contain transcript records, and each transcript to contain exon records.

Also, if I may ask, what is the goal of your project and is it the right tool, since as I mentioned, IsoQuant is designed for eukaryotic organisms and working with alternative splicing?

All the best
Andrey

**Comment by rebeelouise** [comment]
> Dear @rebeelouise 
> 
> 
> 
> In the first message gffutils detect identical IDs in your GFF:
> 
> `ValueError: Duplicate ID cds-NP_073549.1`
> 
> 
> 
> Duplicating IDs, in fact, violate GFF/GTF format in general (even for features of different type, e.g. gene and CDS may not have the same ID), so other tools might not like it as well. I suggest to change duplicating IDs.
> 
> 
> 
> Second message complains about genes not having transcript / exon children records. IsoQuant is primarily designed for eukaryotes and expects each gene to contain transcript records, and each transcript to contain exon records.
> 
> 
> 
> Also, if I may ask, what is the goal of your project and is it the right tool, since as I mentioned, IsoQuant is designed for eukaryotic organisms and working with alternative splicing?
> 
> 
> 
> All the best
> 
> Andrey

Hi Andrey, 

Thanks for your quick response! 

This is often the case when using tools for viral work. Was hoping I could somehow get it to work regardless. I will speak with the writers of polyTailor to see if they are happy to work with me on adapting this to suit my application! Or find an alternative to isoquant for that step in their workflow! 

It's being used to quantify polyA length and look at 3' end of the sequence of RNA. The viral genomes are polyA'd and also launch sgmRNAs from their genomes. I think I have seen people use isoquant on viral stuff before in the literature! 

I guess if you're interested at any point in adding in this as an application - I'd be happy to talk!

**Comment by andrewprzh** [comment]
@rebeelouise 

Adding viral functionality would be interesting, but it's hard to predict the timeline. I'll keep that in mind.

As to GTFs, it thinks it's possible to make a small converter that would correct viral GTFs to make it compatible.

**Comment by andrewprzh** [comment]
By the way, if you could, is it possible to briefly state what data are you using and what kind of analysis you are aiming at?
I am not very much into viral genomes :)

**Comment by rebeelouise** [comment]
> By the way, if you could, is it possible to briefly state what data are you using and what kind of analysis you are aiming at? I am not very much into viral genomes :)

Absolutely! Can I drop you more info via email? :)

**Comment by caaswangzhen** [comment]
> Sure! I don't post it in comments but it can be found in my profile.

##gff-version 3
##annot-version v2.1
##species Gossypium hirsutum
A01	phytozomev13	gene	16115	16321	.	+	.	ID=Gohir.A01G000101.v2.1;Name=Gohir.A01G000101
A01	phytozomev13	mRNA	16115	16321	.	+	.	ID=Gohir.A01G000101.1.v2.1;Name=Gohir.A01G000101.1;pacid=42434259;longest=1;Parent=Gohir.A01G000101.v2.1
A01	phytozomev13	CDS	16115	16321	.	+	0	ID=Gohir.A01G000101.1.v2.1.CDS.1;Parent=Gohir.A01G000101.1.v2.1;pacid=42434259
A01	phytozomev13	gene	36170	42057	.	-	.	ID=Gohir.A01G000201.v2.1;Name=Gohir.A01G000201
A01	phytozomev13	mRNA	36170	42057	.	-	.	ID=Gohir.A01G000201.1.v2.1;Name=Gohir.A01G000201.1;pacid=42436621;longest=1;Parent=Gohir.A01G000201.v2.1
A01	phytozomev13	CDS	41948	42057	.	-	0	ID=Gohir.A01G000201.1.v2.1.CDS.1;Parent=Gohir.A01G000201.1.v2.1;pacid=42436621
A01	phytozomev13	CDS	36170	36236	.	-	1	ID=Gohir.A01G000201.1.v2.1.CDS.2;Parent=Gohir.A01G000201.1.v2.1;pacid=42436621
A01	phytozomev13	gene	48776	52351	.	+	.	ID=Gohir.A01G000301.v2.1;Name=Gohir.A01G000301
A01	phytozomev13	mRNA	48776	52351	.	+	.	ID=Gohir.A01G000301.1.v2.1;Name=Gohir.A01G000301.1;pacid=42434525;longest=1;Parent=Gohir.A01G000301.v2.1
A01	phytozomev13	five_prime_UTR	48776	49271	.	+	.	ID=Gohir.A01G000301.1.v2.1.five_prime_UTR.1;Parent=Gohir.A01G000301.1.v2.1;pacid=42434525
A01	phytozomev13	five_prime_UTR	49796	50613	.	+	.	ID=Gohir.A01G000301.1.v2.1.five_prime_UTR.2;Parent=Gohir.A01G000301.1.v2.1;pacid=42434525
A01	phytozomev13	CDS	50614	51121	.	+	0	ID=Gohir.A01G000301.1.v2.1.CDS.1;Parent=Gohir.A01G000301.1.v2.1;pacid=42434525
A01	phytozomev13	CDS	51628	51713	.	+	2	ID=Gohir.A01G000301.1.v2.1.CDS.2;Parent=Gohir.A01G000301.1.v2.1;pacid=42434525
A01	phytozomev13	CDS	51868	51931	.	+	0	ID=Gohir.A01G000301.1.v2.1.CDS.3;Parent=Gohir.A01G000301.1.v2.1;pacid=42434525
A01	phytozomev13	CDS	52018	52154	.	+	2	ID=Gohir.A01G000301.1.v2.1.CDS.4;Parent=Gohir.A01G000301.1.v2.1;pacid=42434525
A01	phytozomev13	three_prime_UTR	52155	52351	.	+	.	ID=Gohir.A01G000301.1.v2.1.three_prime_UTR.1;Parent=Gohir.A01G000301.1.v2.1;pacid=42434525
A01	phytozomev13	mRNA	48776	52351	.	+	.	ID=Gohir.A01G000301.2.v2.1;Name=Gohir.A01G000301.2;pacid=42434526;longest=0;Parent=Gohir.A01G000301.v2.1
A01	phytozomev13	five_prime_UTR	48776	49271	.	+	.	ID=Gohir.A01G000301.2.v2.1.five_prime_UTR.1;Parent=Gohir.A01G000301.2.v2.1;pacid=42434526
A01	phytozomev13	five_prime_UTR	49796	49817	.	+	.	ID=Gohir.A01G000301.2.v2.1.five_prime_UTR.2;Parent=Gohir.A01G000301.2.v2.1;pacid=42434526
A01	phytozomev13	five_prime_UTR	49974	50613	.	+	.	ID=Gohir.A01G000301.2.v2.1.five_prime_UTR.3;Parent=Gohir.A01G000301.2.v2.1;pacid=42434526
A01	phytozomev13	CDS	50614	51121	.	+	0	ID=Gohir.A01G000301.2.v2.1.CDS.1;Parent=Gohir.A01G000301.2.v2.1;pacid=42434526
A01	phytozomev13	CDS	51628	51713	.	+	2	ID=Gohir.A01G000301.2.v2.1.CDS.2;Parent=Gohir.A01G000301.2.v2.1;pacid=42434526
A01	phytozomev13	CDS	51868	51931	.	+	0	ID=Gohir.A01G000301.2.v2.1.CDS.3;Parent=Gohir.A01G000301.2.v2.1;pacid=42434526
A01	phytozomev13	CDS	52018	52154	.	+	2	ID=Gohir.A01G000301.2.v2.1.CDS.4;Parent=Gohir.A01G000301.2.v2.1;pacid=42434526
A01	phytozomev13	three_prime_UTR	52155	52351	.	+	.	ID=Gohir.A01G000301.2.v2.1.three_prime_UTR.1;Parent=Gohir.A01G000301.2.v2.1;pacid=42434526
A01	phytozomev13	mRNA	48777	52351	.	+	.	ID=Gohir.A01G000301.3.v2.1;Name=Gohir.A01G000301.3;pacid=42434527;longest=0;Parent=Gohir.A01G000301.v2.1
A01	phytozomev13	five_prime_UTR	48777	49271	.	+	.	ID=Gohir.A01G000301.3.v2.1.five_prime_UTR.1;Parent=Gohir.A01G000301.3.v2.1;pacid=42434527
A01	phytozomev13	five_prime_UTR	49796	49817	.	+	.	ID=Gohir.A01G000301.3.v2.1.five_prime_UTR.2;Parent=Gohir.A01G000301.3.v2.1;pacid=42434527
A01	phytozomev13	five_prime_UTR	49897	50613	.	+	.	ID=Gohir.A01G000301.3.v2.1.five_prime_UTR.3;Parent=Gohir.A01G000301.3.v2.1;pacid=42434527
A01	phytozomev13	CDS	50614	51121	.	+	0	ID=Gohir.A01G000301.3.v2.1.CDS.1;Parent=Gohir.A01G000301.3.v2.1;pacid=42434527
A01	phytozomev13	CDS	51628	51713	.	+	2	ID=Gohir.A01G000301.3.v2.1.CDS.2;Parent=Gohir.A01G000301.3.v2.1;pacid=42434527
A01	phytozomev13	CDS	51868	51931	.	+	0	ID=Gohir.A01G000301.3.v2.1.CDS.3;Parent=Gohir.A01G000301.3.v2.1;pacid=42434527
A01	phytozomev13	CDS	52018	52154	.	+	2	ID=Gohir.A01G000301.3.v2.1.CDS.4;Parent=Gohir.A01G000301.3.v2.1;pacid=42434527
A01	phytozomev13	three_prime_UTR	52155	52351	.	+	.	ID=Gohir.A01G000301.3.v2.1.three_prime_UTR.1;Parent=Gohir.A01G000301.3.v2.1;pacid=42434527
A01	phytozomev13	mRNA	48777	52351	.	+	.	ID=Gohir.A01G000301.4.v2.1;Name=Gohir.A01G000301.4;pacid=42434528;longest=0;Parent=Gohir.A01G000301.v2.1
A01	phytozomev13	five_prime_UTR	48777	49271	.	+	.	ID=Gohir.A01G000301.4.v2.1.five_prime_UTR.1;Parent=Gohir.A01G000301.4.v2.1;pacid=42434528
A01	phytozomev13	five_prime_UTR	49800	49817	.	+	.	ID=Gohir.A01G000301.4.v2.1.five_prime_UTR.2;Parent=Gohir.A01G000301.4.v2.1;pacid=42434528
A01	phytozomev13	five_prime_UTR	49897	50613	.	+	.	ID=Gohir.A01G000301.4.v2.1.five_prime_UTR.3;Parent=Gohir.A01G000301.4.v2.1;pacid=42434528
A01	phytozomev13	CDS	50614	51121	.	+	0	ID=Gohir.A01G000301.4.v2.1.CDS.1;Parent=Gohir.A01G000301.4.v2.1;pacid=42434528
A01	phytozomev13	CDS	51868	51931	.	+	2	ID=Gohir.A01G000301.4.v2.1.CDS.2;Parent=Gohir.A01G000301.4.v2.1;pacid=42434528
A01	phytozomev13	CDS	52018	52171	.	+	1	ID=Gohir.A01G000301.4.v2.1.CDS.3;Parent=Gohir.A01G000301.4.v2.1;pacid=42434528
A01	phytozomev13	three_prime_UTR	52172	52351	.	+	.	ID=Gohir.A01G000301.4.v2.1.three_prime_UTR.1;Parent=Gohir.A01G000301.4.v2.1;pacid=42434528






Hello,

When running isoquant, the input GFF3 file only contains CDS but no exons. Will it still work properly?
My friend encountered this issue.

2025-03-15 21:28:16,929 - WARNING - Malformed transcript Gohir.D03G068901.1.v2.1 has no exons
2025-03-15 21:28:19,272 - WARNING - Malformed transcript Gohir.D03G068901.1.v2.1 has no exons

**Comment by caaswangzhen** [comment]
2025-04-10 00:04:41,011 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesconcurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wangy/anaconda3/envs/isoquant1/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/wangy/anaconda3/envs/isoquant1/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/wangy/anaconda3/envs/isoquant1/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/wangy/anaconda3/envs/isoquant1/share/isoquant-3.6.3-0/src/dataset_processor.py", line 289, in construct_models_in_parallel
    model_constructor.process(assignment_storage)
  File "/home/wangy/anaconda3/envs/isoquant1/share/isoquant-3.6.3-0/src/graph_based_model_construction.py", line 139, in process
    transcript_joiner = TranscriptToGeneJoiner(self.transcript_model_storage, self.gene_info)
  File "/home/wangy/anaconda3/envs/isoquant1/share/isoquant-3.6.3-0/src/graph_based_model_construction.py", line 959, in __init__
    self.gene_introns[gene_id].update(self.gene_info.all_isoforms_introns[transcript_id])
KeyError: 'Gohir.A06G044066.2.v2.1'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wangy/anaconda3/envs/isoquant1/bin/isoquant.py", line 819, in <module>
    main(sys.argv[1:])
  File "/home/wangy/anaconda3/envs/isoquant1/bin/isoquant.py", line 813, in main
    run_pipeline(args)
  File "/home/wangy/anaconda3/envs/isoquant1/bin/isoquant.py", line 763, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/home/wangy/anaconda3/envs/isoquant1/share/isoquant-3.6.3-0/src/dataset_processor.py", line 456, in process_all_samples
    self.process_sample(sample)
  File "/home/wangy/anaconda3/envs/isoquant1/share/isoquant-3.6.3-0/src/dataset_processor.py", line 509, in process_sample
    self.process_assigned_reads(sample, saves_file)
  File "/home/wangy/anaconda3/envs/isoquant1/share/isoquant-3.6.3-0/src/dataset_processor.py", line 698, in process_assigned_reads
    for read_stat_counter, tsc in results:
  File "/home/wangy/anaconda3/envs/isoquant1/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/wangy/anaconda3/envs/isoquant1/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/home/wangy/anaconda3/envs/isoquant1/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/wangy/anaconda3/envs/isoquant1/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
KeyError: 'Gohir.A06G044066.2.v2.1'

**Comment by andrewprzh** [comment]
Please, re-open if any problem is still there.
