### ISSUE TITLE
KeyError: 'novel'

### ISSUE THREAD

**Issue by kudasonya** [ablab/IsoQuant#30]
Hello, 

I am trying to run IsoQuant on some premapped ONT data. Could you please help me resolve this error I'm getting?

```
2022-05-24 15:44:18,637 - INFO - Processing chromosome chrM
2022-05-24 15:44:18,650 - INFO - Loading read assignments from isoquant_bam_out/Caudate/aux/Caudate.save_chrM
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 226, in construct_models_in_parallel
    tmp_gff_printer.dump(model_constructor)
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/share/isoquant-2.2.1-0/src/transcript_printer.py", line 85, in dump
    strand = transcript_model_constructor.gene_info.isoform_strands[model.reference_transcript]
KeyError: 'novel'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/bin/isoquant.py", line 486, in <module>
    main(sys.argv[1:])
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/bin/isoquant.py", line 480, in main
    run_pipeline(args)
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/bin/isoquant.py", line 466, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 265, in process_all_samples
    self.process_sample(sample)
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 293, in process_sample
    self.process_assigned_reads(sample, saves_file)
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 359, in process_assigned_reads
    self.io_support) for chr_id in chr_ids], chunksize=1)
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/ei/software/testing/python_miniconda/4.10.3_py3.9_sk/x86_64/envs/isoquant/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'novel'
```

**Comment by andrewprzh** [comment]
Hi @kudasonya 

I believe this issue was fixed in version [2.2.2 ](https://github.com/ablab/IsoQuant/releases/tag/v2.2.2). Could you try it please?
Should be available via conda as well.

Best
Andrey

**Comment by kudasonya** [comment]
Thank you for a quick response @andrewprzh! I will try that.

**Comment by yjiang296** [comment]
Hello there. I met this issue again. My version is 3.5.0. Could you please help me?

**Comment by yjiang296** [comment]
> Hello there. I met this issue again. My version is 3.5.0. Could you please help me?
My scripts:

isoquant.py --reference *.fa \
--genedb *.gff3 \
--fastq *.fq \
--data_type pacbio_ccs \
--threads 50 \
--sqanti_output \
--check_canonical \
--count_exons \
-o /data21/yjiang22/hybrid_full_length/IsoQuant

**Comment by andrewprzh** [comment]
@yjiang296 

could you send me the isoquant.log file?

**Comment by yjiang296** [comment]
I have figured it out! Thank you for your response.
