### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by zhou-ran** [ablab/IsoQuant#31]
Hi Andrey, 

Thanks for you quick response.

I meet this error in IsoQuant 2.2.1 for processing gtf file download from https://ftp.ensembl.org/pub/release-101/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.101.gtf.gz, here is the log file

```
Command line: isoquant.py -d pacbio_ccs --bam data/minimap2/SRX9116756.bam -l SRX9116756 --reference /NAS/ref/Drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.dna.toplevel.fa.gz --complete_genedb --genedb /NAS/ref/Drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.101.sorted.gtf.db --output SRX9116756 --count_exons
2022-06-05 10:31:58,140 - INFO - Running IsoQuant version 2.2.1
2022-06-05 10:31:58,153 - INFO -  === IsoQuant pipeline started === 
2022-06-05 10:31:58,153 - INFO - Loading gene database from /NAS/zym/bib/ref/Drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.101.sorted.gtf.db
2022-06-05 10:31:58,261 - INFO - Loading reference genome from /NAS/zym/bib/ref/Drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.dna.toplevel.fa.gz
2022-06-05 10:32:02,181 - INFO - Processing 1 sample
2022-06-05 10:32:02,182 - INFO - Processing sample SRX9116756
2022-06-05 10:32:02,182 - INFO - Sample has 1 BAM file: data/minimap2/SRX9116756.bam
2022-06-05 10:32:02,182 - INFO - Assigning reads to isoforms
2022-06-05 10:32:02,745 - INFO - Processing chromosome 2R
2022-06-05 10:32:02,935 - INFO - Processing chromosome 3R
2022-06-05 10:32:03,072 - INFO - Processing chromosome 2L
2022-06-05 10:32:03,215 - INFO - Processing chromosome 4
2022-06-05 10:32:03,297 - INFO - Processing chromosome Unmapped_Scaffold_8_D1580_D1567
2022-06-05 10:32:03,414 - INFO - Processing chromosome 211000022280494
2022-06-05 10:32:03,480 - INFO - Processing chromosome 211000022278449
2022-06-05 10:32:03,485 - INFO - Processing chromosome 211000022278279
2022-06-05 10:32:03,519 - INFO - Processing chromosome Y
2022-06-05 10:32:03,555 - INFO - Processing chromosome rDNA
2022-06-05 10:32:03,555 - INFO - Processing chromosome mitochondrion_genome
2022-06-05 10:32:03,555 - INFO - Processing chromosome 211000022279165
2022-06-05 10:32:03,577 - INFO - Processing chromosome 211000022278760
2022-06-05 10:32:03,579 - INFO - Processing chromosome 211000022278436
2022-06-05 10:32:03,581 - INFO - Processing chromosome 3L
2022-06-05 10:32:03,625 - INFO - Processing chromosome X
2022-06-05 10:32:04,590 - INFO - Finished processing chromosome 211000022278279
2022-06-05 10:32:04,593 - INFO - Finished processing chromosome 211000022278449
2022-06-05 10:32:04,668 - INFO - Finished processing chromosome 211000022279165
2022-06-05 10:32:04,684 - INFO - Finished processing chromosome 211000022278760
2022-06-05 10:32:04,684 - INFO - Finished processing chromosome 211000022278436
2022-06-05 10:32:04,725 - INFO - Finished processing chromosome Unmapped_Scaffold_8_D1580_D1567
2022-06-05 10:32:04,881 - INFO - Finished processing chromosome 211000022280494
2022-06-05 10:32:04,898 - INFO - Processing chromosome 211000022279188
2022-06-05 10:32:04,902 - INFO - Processing chromosome 211000022279264
2022-06-05 10:32:05,063 - INFO - Processing chromosome 211000022279392
2022-06-05 10:32:05,117 - INFO - Processing chromosome 211000022279681
2022-06-05 10:32:05,139 - INFO - Processing chromosome 211000022280328
2022-06-05 10:32:05,193 - INFO - Processing chromosome 211000022280341
2022-06-05 10:32:05,210 - INFO - Processing chromosome 211000022280347
2022-06-05 10:32:05,720 - INFO - Finished processing chromosome 211000022279188
2022-06-05 10:32:05,810 - INFO - Finished processing chromosome 211000022279264
2022-06-05 10:32:05,878 - INFO - Finished processing chromosome 211000022279392
2022-06-05 10:32:05,963 - INFO - Finished processing chromosome 211000022279681
2022-06-05 10:32:05,964 - INFO - Finished processing chromosome 211000022280328
2022-06-05 10:32:06,013 - INFO - Finished processing chromosome 211000022280341
2022-06-05 10:32:06,015 - INFO - Processing chromosome 211000022280481
2022-06-05 10:32:06,103 - INFO - Processing chromosome 211000022280703
2022-06-05 10:32:06,114 - INFO - Finished processing chromosome 211000022280347
2022-06-05 10:32:06,589 - INFO - Finished processing chromosome 211000022280481
2022-06-05 10:32:06,652 - INFO - Finished processing chromosome 211000022280703
2022-06-05 10:32:10,980 - INFO - Finished processing chromosome rDNA
2022-06-05 10:32:23,531 - INFO - Finished processing chromosome Y
2022-06-05 10:32:32,133 - INFO - Finished processing chromosome 4
2022-06-05 10:40:00,066 - INFO - Finished processing chromosome X
2022-06-05 10:41:08,435 - INFO - Finished processing chromosome 2L
2022-06-05 10:41:10,050 - INFO - Finished processing chromosome 3L
2022-06-05 10:41:44,931 - INFO - Finished processing chromosome 2R
2022-06-05 10:42:57,853 - INFO - Finished processing chromosome 3R

```

here is the error

```
IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issues
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/NAS/zym/env/miniconda3/envs/isoquant/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/NAS/zym/env/miniconda3/envs/isoquant/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 129, in assign_reads_in_parallel
    gene_info = GeneInfo(g, gffutils_db, args.delta)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/gene_info.py", line 132, in __init__
    self.set_junction_profiles(self.all_isoforms_introns, self.all_isoforms_exons)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/gene_info.py", line 442, in set_junction_profiles
    transcript_region = self.transcript_region(t.id)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/gene_info.py", line 488, in transcript_region
    return (self.transcript_start(transcript_id), self.transcript_end(transcript_id))
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/gene_info.py", line 482, in transcript_start
    return self.all_isoforms_exons[transcript_id][0][0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/NAS/zym/env/miniconda3/envs/isoquant/bin/isoquant.py", line 486, in <module>
    main(sys.argv[1:])
  File "/NAS/zym/env/miniconda3/envs/isoquant/bin/isoquant.py", line 480, in main
    run_pipeline(args)
  File "/NAS/zym/env/miniconda3/envs/isoquant/bin/isoquant.py", line 466, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 265, in process_all_samples
    self.process_sample(sample)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 279, in process_sample
    self.assign_reads(sample)
  File "/NAS/zym/env/miniconda3/envs/isoquant/share/isoquant-2.2.1-0/src/dataset_processor.py", line 303, in assign_reads
    results = pool.starmap(assign_reads_in_parallel, [(sample, chr_id, c, self.args, self.read_grouper,
  File "/NAS/zym/env/miniconda3/envs/isoquant/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/NAS/zym/env/miniconda3/envs/isoquant/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range
```

 then i found the gene (FBgn0013687) caused index error, and after skip this gene for creating db file, isoquant worked well.

So, i think there some error in parsing or other?

Ran

**Comment by andrewprzh** [comment]
Dear Ran

Thanks a lot for the data and all the information - that made it way easier to understand the problem!

Yes, you are right about the parsing. From what I see the problem arises in gffutils library, which is used from parsing GTFs. For some reason (most likely to avoid duplicating IDs in the database), gffutils changes transcript id from `FBgn0013687` to `FBgn0013687_1`, because its parent gene has the same id (`FBgn0013687`). However, the exon still belongs to transcript `FBgn0013687` and thus transcript entry appears to be empty. I will report this issue on their GitHub and tag you there as well. 

Current workaround is either to remove it as you did, or change the transcript id in both transcript and exon lines. 

Best
Andrey

**Comment by zhou-ran** [comment]
Hi Andrey,

Thanks for your time and effort

Cheers,
Ran

**Comment by andrewprzh** [comment]
Hi Ran

According to https://mblab.wustl.edu/GTF22.html, it seems that `gene_id` and `transcript_id` should be globally unique, so it's weird how they got in the official annotation. 

Best
Andrey

**Comment by zhou-ran** [comment]
Hi Andrey, 

Thanks again. 

Yes, It's not a bug for IsoQuant. 

Cheers,
Ran

**Comment by andrewprzh** [comment]
Hi Ran

Sure, but it's good to be aware about internal libs, especially since the annotation is the official one. Reported the case to gffutils GitHub https://github.com/daler/gffutils/issues/194

Best
Andrey

**Comment by andrewprzh** [comment]
Dear @zhou-ran 

In fact, it appears that gffutils does raises an error when duplicate ids appear, but for some reason this error reporting was silenced in IsoQuant conversion. Will be fixed in the next release. Thank you!

Best
Andrey
