### ISSUE TITLE
KeyError with chromosome numbers?

### ISSUE THREAD

**Issue by lhkelley** [ablab/IsoQuant#35]
Hi,

I've been trying to use IsoQuant to count reads from bam files with C. elegans data generated by Nanopore sequencing. However, I keep get the following KeyError, followed by a chromosome number (see below). I think something must be wrong with the GTF annotation file, but I've tried different ones and I'm still not sure what the issue is. Thank you!

isoquant.py --genedb Caenorhabditis_elegans.WBcel235.54.gff3 --bam all_reads_wb_mrna_transc_sorted.bam --reference GCF_000002985.6_WBcel235_genomic.fna --data_type nanopore -o 19July
WARNING! Output folder already exists, some files may be overwritten
2022-07-19 09:50:05,406 - INFO - Running IsoQuant version 2.3.0
2022-07-19 09:50:05,412 - WARNING - 19July/00_all_reads_wb_mrna_transc_sorted folder already exists, some files may be overwritten
2022-07-19 09:50:05,412 - WARNING - 19July/00_all_reads_wb_mrna_transc_sorted/aux folder already exists, some files may be overwritten
2022-07-19 09:50:05,417 - INFO -  === IsoQuant pipeline started === 
2022-07-19 09:50:05,424 - INFO - Converting gene annotation file to .db format (takes a while)...
2022-07-19 11:40:12,537 - INFO - Gene database written to /home/lhkelley/subset3_10July/19July/Caenorhabditis_elegans.WBcel235.54.db
2022-07-19 11:40:12,541 - INFO - Provide this database next time to avoid excessive conversion
2022-07-19 11:40:12,542 - INFO - Loading gene database from /home/lhkelley/subset3_10July/19July/Caenorhabditis_elegans.WBcel235.54.db
2022-07-19 11:40:12,705 - INFO - Loading reference genome from GCF_000002985.6_WBcel235_genomic.fna
2022-07-19 11:40:27,929 - INFO - Processing 1 sample
2022-07-19 11:40:27,931 - INFO - Processing sample 00_all_reads_wb_mrna_transc_sorted
2022-07-19 11:40:27,933 - INFO - Sample has 1 BAM file: all_reads_wb_mrna_transc_sorted.bam
2022-07-19 11:40:27,933 - INFO - Assigning reads to isoforms
IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issues
Traceback (most recent call last):
  File "/home/lhkelley/miniconda3/envs/isoquant/bin/isoquant.py", line 499, in <module>
    main(sys.argv[1:])
  File "/home/lhkelley/miniconda3/envs/isoquant/bin/isoquant.py", line 493, in main
    run_pipeline(args)
  File "/home/lhkelley/miniconda3/envs/isoquant/bin/isoquant.py", line 479, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/home/lhkelley/miniconda3/envs/isoquant/share/isoquant-2.3.0-0/src/dataset_processor.py", line 265, in process_all_samples
    self.process_sample(sample)
  File "/home/lhkelley/miniconda3/envs/isoquant/share/isoquant-2.3.0-0/src/dataset_processor.py", line 279, in process_sample
    self.assign_reads(sample)
  File "/home/lhkelley/miniconda3/envs/isoquant/share/isoquant-2.3.0-0/src/dataset_processor.py", line 306, in assign_reads
    for (chr_id, c) in chrom_clusters], chunksize=1)
  File "/home/lhkelley/miniconda3/envs/isoquant/share/isoquant-2.3.0-0/src/dataset_processor.py", line 306, in <listcomp>
    for (chr_id, c) in chrom_clusters], chunksize=1)
KeyError: 'V'

**Comment by almiheenko** [comment]
Dear Leanne,

Probably the chromosome names in the GTF file and in the FASTA file do not match (e.g., "V" in the GTF file and "chrV" in the FASTA file). You can try to download another version of the reference genome that corresponds to the annotation (maybe try here https://ensembl.org/Caenorhabditis_elegans/Info/Index). But if you use another reference, you will need to remap reads to it (or use a FASTQ file as an input to IsoQuant).
Please let me know if you have any further questions.

Best,
Alla

**Comment by lhkelley** [comment]
Hi Alla,

That was indeed the problem! Thank you!
