### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by derijkp** [ablab/IsoQuant#36]
Hi,

I received the following error when running isoquant 3.0.0alpha:
TypeError: '<' not supported between instances of 'NoneType' and 'str'' error (full traceback below).
Unfortunately I cannot share the data. However, it may help that I could solve (work around) the error by adding checks for None ("if feature_id is not None:" and similar) everywhere data is added to all_features in AssignedFeatureCounter in long_read_counter.py

Regards,

Peter

2022-08-25 12:10:28,362 - INFO - Finished processing chromosome chrX
Traceback (most recent call last):
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/bin/isoquant.py", line 514, in <module>
    main(sys.argv[1:])
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/bin/isoquant.py", line 508, in main
    run_pipeline(args)
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/bin/isoquant.py", line 494, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/share/isoquant-3.0.0/src/dataset_processor.py", line 208, in process_all_samples
    self.process_sample(sample)
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/share/isoquant-3.0.0/src/dataset_processor.py", line 237, in process_sample
    self.process_assigned_reads(sample, saves_file)
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/share/isoquant-3.0.0/src/dataset_processor.py", line 315, in process_assigned_reads
    read_stat_counters, transcript_model_storages = [x[0] for x in results], [x[1] for x in results]
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/share/isoquant-3.0.0/src/dataset_processor.py", line 315, in <listcomp>
    read_stat_counters, transcript_model_storages = [x[0] for x in results], [x[1] for x in results]
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/share/isoquant-3.0.0/src/dataset_processor.py", line 151, in construct_models_in_parallel
    processor.global_counter.dump()
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/share/isoquant-3.0.0/src/long_read_counter.py", line 111, in dump
    p.dump()
  File "/net/breva/data/complgen/bin/isoquant-3.0.0-x86_64/share/isoquant-3.0.0/src/long_read_counter.py", line 212, in dump
    all_features = sorted(self.all_features)
TypeError: '<' not supported between instances of 'NoneType' and 'str'
child process exited abnormally

**Comment by andrewprzh** [comment]
Hi 

Would you like me to create a branch where such checks would be inserted?
The error seems familiar and I recall fixing it, could another one though.

Best
Andrey

**Comment by derijkp** [comment]
Hi,

I worked with the 3.0.0alpha release, not the latest commits, so it may have been fixed there. Having made a local patch is sufficient for me (no branch needed); just reported the error to keep it out of future releases.

Regards,

Peter

**Comment by andrewprzh** [comment]
Please, reopen if the problem is still there.
