### ISSUE TITLE
The next step after alignment, isquant runs out of memory causing a crash

### ISSUE THREAD

**Issue by zjhcarbonic** [ablab/IsoQuant#52]
Hello!
After the alignment is complete, isoquant processes the data by chromosome. isoquant does run, however python3 consumes a lot of memory until it runs out of memory and crashes. I have only set up 2 threads with 54G memory.

![image](https://user-images.githubusercontent.com/46081766/211990853-4c832341-2fbc-4b5c-98cb-8b10d0824107.png)

(isoquant) zhao@zhao-virtual-machine:~/shareDisk/hc320_1/nanopore_ont_cDNA_analysis$ ./IsoQuant-3.1.0/isoquant.py --resume -t 2 -o nip 
2023-01-12 12:47:11,498 - INFO - Running IsoQuant version 3.1.0
2023-01-12 12:47:11,499 - INFO - Loading parameters of the previous run, all arguments will be ignored
2023-01-12 12:47:11,512 - INFO -  === IsoQuant pipeline started === 
2023-01-12 12:47:11,512 - INFO - Gene annotation file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/Oryza_sativa.IRGSP-1.0.55.chr.db
2023-01-12 12:47:11,513 - INFO - Index file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/Oryza_sativa.IRGSP-1.0.dna.toplevel_k14_idx
2023-01-12 12:47:11,514 - INFO - BED file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/Oryza_sativa.IRGSP-1.0.55.chr.bed
2023-01-12 12:47:11,514 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_1.pychoppered.fq.min50_e125fb_47e0e6_fc1998.bam
2023-01-12 12:47:11,515 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_2.pychoppered.fq.min50_43a6d3_47e0e6_fc1998.bam
2023-01-12 12:47:11,515 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_3.pychoppered.fq.min50_4f396f_47e0e6_fc1998.bam
2023-01-12 12:47:11,516 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_1/aux/N_1_N_1_1.pychoppered.fq.min50_73592f_47e0e6_fc1998.bam
2023-01-12 12:47:11,516 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_1/aux/N_1_N_1_2.pychoppered.fq.min50_479173_47e0e6_fc1998.bam
2023-01-12 12:47:11,517 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_1/aux/N_1_N_1_3.pychoppered.fq.min50_fece26_47e0e6_fc1998.bam
2023-01-12 12:47:11,517 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_2/aux/N_2_N_2_1.pychoppered.fq.min50_6f7995_47e0e6_fc1998.bam
2023-01-12 12:47:11,518 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_2/aux/N_2_N_2_2.pychoppered.fq.min50_8e1d9c_47e0e6_fc1998.bam
2023-01-12 12:47:11,518 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_2/aux/N_2_N_2_3.pychoppered.fq.min50_ba7e39_47e0e6_fc1998.bam
2023-01-12 12:47:11,519 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_3/aux/N_3_N_3_1.pychoppered.fq.min50_741c25_47e0e6_fc1998.bam
2023-01-12 12:47:11,519 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_3/aux/N_3_N_3_2.pychoppered.fq.min50_19f2ac_47e0e6_fc1998.bam
2023-01-12 12:47:11,519 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_3/aux/N_3_N_3_3.pychoppered.fq.min50_29a1eb_47e0e6_fc1998.bam
2023-01-12 12:47:11,520 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_4/aux/N_4_N_4_1.pychoppered.fq.min50_f85025_47e0e6_fc1998.bam
2023-01-12 12:47:11,521 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_4/aux/N_4_N_4_2.pychoppered.fq.min50_09b03a_47e0e6_fc1998.bam
2023-01-12 12:47:11,521 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_4/aux/N_4_N_4_3.pychoppered.fq.min50_4d54ec_47e0e6_fc1998.bam
2023-01-12 12:47:11,521 - INFO - Loading gene database from /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/Oryza_sativa.IRGSP-1.0.55.chr.db
2023-01-12 12:47:11,525 - INFO - Loading reference genome from Oryza_sativa.IRGSP-1.0.dna.toplevel.fa
2023-01-12 12:47:15,478 - INFO - Processing 5 samples
2023-01-12 12:47:15,478 - INFO - Processing sample N_0
2023-01-12 12:47:15,479 - INFO - Sample has 3 BAM files: /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_1.pychoppered.fq.min50_e125fb_47e0e6_fc1998.bam, /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_2.pychoppered.fq.min50_43a6d3_47e0e6_fc1998.bam, /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_3.pychoppered.fq.min50_4f396f_47e0e6_fc1998.bam
2023-01-12 12:47:15,479 - INFO - Collecting read alignments
2023-01-12 12:47:25,505 - INFO - Detected processed reads for 1
2023-01-12 12:47:25,537 - INFO - Detected processed reads for 3
2023-01-12 12:47:25,982 - INFO - Processing chromosome 4
2023-01-12 12:47:25,982 - INFO - Processing chromosome 2

**Comment by andrewprzh** [comment]
Dear @zjhcarbonic 

Yes, IsoQuant is still quite greedy in terms of RAM, we are working on that. Hope we will have a more efficient version sometime soon.

Currenly I can suggest to try experimental `--low_memory` option and reduce the number of threads to 1. 

Best
Andrey

**Comment by zjhcarbonic** [comment]
thanks for your help！
I tried the --low_memory option and it didn't work. Setting the number of threads to 1 return an error. Maybe I should increase the memory.

(isoquant) zhao@zhao-virtual-machine:~/shareDisk/hc320_1/nanopore_ont_cDNA_analysis$ ./IsoQuant-3.1.0/isoquant.py -o nip -t 1 --resume
2023-01-13 16:38:00,409 - INFO - Running IsoQuant version 3.1.0
2023-01-13 16:38:00,410 - INFO - Loading parameters of the previous run, all arguments will be ignored
2023-01-13 16:38:00,451 - INFO -  === IsoQuant pipeline started === 
2023-01-13 16:38:00,452 - INFO - Gene annotation file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/Oryza_sativa.IRGSP-1.0.55.chr.db
2023-01-13 16:38:00,452 - INFO - Index file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/Oryza_sativa.IRGSP-1.0.dna.toplevel_k14_idx
2023-01-13 16:38:00,453 - INFO - BED file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/Oryza_sativa.IRGSP-1.0.55.chr.bed
2023-01-13 16:38:00,454 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_1.pychoppered.fq.min50_e125fb_47e0e6_fc1998.bam
2023-01-13 16:38:00,454 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_2.pychoppered.fq.min50_43a6d3_47e0e6_fc1998.bam
2023-01-13 16:38:00,455 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_3.pychoppered.fq.min50_4f396f_47e0e6_fc1998.bam
2023-01-13 16:38:00,455 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_1/aux/N_1_N_1_1.pychoppered.fq.min50_73592f_47e0e6_fc1998.bam
2023-01-13 16:38:00,456 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_1/aux/N_1_N_1_2.pychoppered.fq.min50_479173_47e0e6_fc1998.bam
2023-01-13 16:38:00,456 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_1/aux/N_1_N_1_3.pychoppered.fq.min50_fece26_47e0e6_fc1998.bam
2023-01-13 16:38:00,457 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_2/aux/N_2_N_2_1.pychoppered.fq.min50_6f7995_47e0e6_fc1998.bam
2023-01-13 16:38:00,457 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_2/aux/N_2_N_2_2.pychoppered.fq.min50_8e1d9c_47e0e6_fc1998.bam
2023-01-13 16:38:00,458 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_2/aux/N_2_N_2_3.pychoppered.fq.min50_ba7e39_47e0e6_fc1998.bam
2023-01-13 16:38:00,458 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_3/aux/N_3_N_3_1.pychoppered.fq.min50_741c25_47e0e6_fc1998.bam
2023-01-13 16:38:00,459 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_3/aux/N_3_N_3_2.pychoppered.fq.min50_19f2ac_47e0e6_fc1998.bam
2023-01-13 16:38:00,460 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_3/aux/N_3_N_3_3.pychoppered.fq.min50_29a1eb_47e0e6_fc1998.bam
2023-01-13 16:38:00,460 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_4/aux/N_4_N_4_1.pychoppered.fq.min50_f85025_47e0e6_fc1998.bam
2023-01-13 16:38:00,461 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_4/aux/N_4_N_4_2.pychoppered.fq.min50_09b03a_47e0e6_fc1998.bam
2023-01-13 16:38:00,461 - INFO - Bam alignment file found. Using /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_4/aux/N_4_N_4_3.pychoppered.fq.min50_4d54ec_47e0e6_fc1998.bam
2023-01-13 16:38:00,462 - INFO - Loading gene database from /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/Oryza_sativa.IRGSP-1.0.55.chr.db
2023-01-13 16:38:00,512 - INFO - Loading reference genome from Oryza_sativa.IRGSP-1.0.dna.toplevel.fa
2023-01-13 16:38:30,250 - INFO - Processing 5 samples
2023-01-13 16:38:30,250 - INFO - Processing sample N_0
2023-01-13 16:38:30,250 - INFO - Sample has 3 BAM files: /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_1.pychoppered.fq.min50_e125fb_47e0e6_fc1998.bam, /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_2.pychoppered.fq.min50_43a6d3_47e0e6_fc1998.bam, /home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/nip/N_0/aux/N_0_N_0_3.pychoppered.fq.min50_4f396f_47e0e6_fc1998.bam
2023-01-13 16:38:30,251 - INFO - Collecting read alignments
2023-01-13 16:38:44,050 - INFO - Detected processed reads for 1
Traceback (most recent call last):
  File "./IsoQuant-3.1.0/isoquant.py", line 592, in <module>
    main(sys.argv[1:])
  File "./IsoQuant-3.1.0/isoquant.py", line 586, in main
    run_pipeline(args)
  File "./IsoQuant-3.1.0/isoquant.py", line 542, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/IsoQuant-3.1.0/src/dataset_processor.py", line 245, in process_all_samples
    self.process_sample(sample)
  File "/home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/IsoQuant-3.1.0/src/dataset_processor.py", line 259, in process_sample
    self.collect_reads(sample)
  File "/home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/IsoQuant-3.1.0/src/dataset_processor.py", line 303, in collect_reads
    processed_reads, read_groups = zip(*results)
  File "/home/zhao/shareDisk/hc320_1/nanopore_ont_cDNA_analysis/IsoQuant-3.1.0/src/dataset_processor.py", line 41, in collect_reads_in_parallel
    read_grouper.read_groups.append(g.strip())
AttributeError: 'set' object has no attribute 'append'

**Comment by andrewprzh** [comment]
@zjhcarbonic 

I you have the possibility to increase RAM, I suggest to give it a try.

The last error you've sent looks like a bug, will make a bug fix release soon, thanks for reporting!

Best
Andrey

**Comment by zjhcarbonic** [comment]
@andrewprzh 
ok, Thank you for your attention to this matter.

**Comment by andrewprzh** [comment]
@zjhcarbonic 

The second error should be fixed in https://github.com/ablab/IsoQuant/releases/tag/v3.1.1

Memory consumption is still to be improved.

Best
Andrey
