### ISSUE TITLE
ValueError: file has no sequences defined (mode='rb'), Consider opening with check_sq=False

### ISSUE THREAD

**Issue by theosusanto** [ablab/IsoQuant#77]
Hi everyone,

I was running IsoQuant version 3.1.2 on pacbio ccs fastq.gz file:
I received this error at "Collecting read alignments" step:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/tsusanto/miniconda/envs/isoquant/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/tsusanto/miniconda/envs/isoquant/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/tsusanto/miniconda/envs/isoquant/share/isoquant-3.1.2-1/src/dataset_processor.py", line 52, in collect_reads_in_parallel
    bam_file_pairs = [(pysam.AlignmentFile(bam, "rb"), bam) for bam in bam_files]
  File "/home/tsusanto/miniconda/envs/isoquant/share/isoquant-3.1.2-1/src/dataset_processor.py", line 52, in <listcomp>
    bam_file_pairs = [(pysam.AlignmentFile(bam, "rb"), bam) for bam in bam_files]
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 1000, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tsusanto/miniconda/envs/isoquant/bin/isoquant.py", line 609, in <module>
    main(sys.argv[1:])
  File "/home/tsusanto/miniconda/envs/isoquant/bin/isoquant.py", line 603, in main
    run_pipeline(args)
  File "/home/tsusanto/miniconda/envs/isoquant/bin/isoquant.py", line 559, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/home/tsusanto/miniconda/envs/isoquant/share/isoquant-3.1.2-1/src/dataset_processor.py", line 245, in process_all_samples
    self.process_sample(sample)
  File "/home/tsusanto/miniconda/envs/isoquant/share/isoquant-3.1.2-1/src/dataset_processor.py", line 259, in process_sample
    self.collect_reads(sample)
  File "/home/tsusanto/miniconda/envs/isoquant/share/isoquant-3.1.2-1/src/dataset_processor.py", line 298, in collect_reads
    results = pool.starmap(collect_reads_in_parallel, [(sample, chr_id, self.args, self.read_grouper,
  File "/home/tsusanto/miniconda/envs/isoquant/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/tsusanto/miniconda/envs/isoquant/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
```

I checked the .bam file generated at output/sample.fastq/aux, and it seemed alright.
This run was terminated earlier at indexing reference step. 
Could you please advice? Thank you!

Best regards,
Theo

**Comment by andrewprzh** [comment]
Dear @theosusanto 

This looks really odd. Could you please the entire isoquant.log file?

Best
Andrey

**Comment by andrewprzh** [comment]
Dear @theosusanto 

Wow, that is quite surprising. Anyway, happy to hear your run eventually finished. Let me know if you encounter any other problems.

Meanwhile, the next release 3.2 should be more stable and require significantly less RAM.

Best
Andrey

**Comment by andrewprzh** [comment]
IsoQuant 3.2 is released, please reopen issue if these problems occur again.

Best
Andrey
