### ISSUE TITLE
gtf2db.py Error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by sandaruwanrat** [ablab/IsoQuant#87]
Hello,

I was trying to use IsoQuant for a arabidopsis custom genome with custom gtf file. I am getting following error from gtf2bed conversion.

`- INFO - Converting gene annotation file u/isoquant_ana/ruby_all/At_array.v2.db to .bed format
Traceback (most recent call last):
  File "u/miniconda3/envs/isoquant/bin/isoquant.py", line 687, in <module>
    main(sys.argv[1:])
  File "u/miniconda3/envs/isoquant/bin/isoquant.py", line 681, in main
    run_pipeline(args)
  File "u/miniconda3/envs/isoquant/bin/isoquant.py", line 630, in run_pipeline
    args.input_data = dataset_mapper.map_reads(args)
  File "u/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/read_mapper.py", line 52, in map_reads
    annotation_file = find_annotation(self.aligner, args)
  File "u/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/read_mapper.py", line 262, in find_annotation
    db2bed(bed_fname, args.genedb)
  File "u/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/gtf2db.py", line 70, in db2bed
    transcript_start = exons[0][0]
IndexError: list index out of range`

Thank you very much.

**Comment by andrewprzh** [comment]
Dear @sandaruwanrat 

Surprisingly, minimap's default tool for conversion (paftools.js  gff2bed) also fails on this GTF:
```
./paftools.js  gff2bed -j At_array.v2.gtf > At_array.v2.paftools.bed
./paftools.js:1664: Error: No transcript_id
		if (id == null) throw Error("No transcript_id");
                  ^
Error: No transcript_id
```

It also seems that gffutils which I use in IsoQuant behaves weirdly on non standard gene entries, e.g.
```
AT2TE02465_Chr2_566757_582571   Araport11       transposable_element_gene       1116    2941    .       +       .        gene_id "AT2G02190"; transcript_id "AT2G02190"
AT2TE02465_Chr2_566757_582571   Araport11       mRNA    1116    2941    .       +       .        gene_id "AT2G02190"; transcript_id "AT2G02190.1"
AT2TE02465_Chr2_566757_582571   Araport11       exon    1116    2941    .       +       .        gene_id "AT2G02190"; transcript_id "AT2G02190.1"
```

For some reason it changes mRNA id to `mRNA_1||AT2G02190` instead of using the provided `transcript_id "AT2G02190.1"`.
I'll take a further look at this.

Best
Andrey

**Comment by sandaruwanrat** [comment]
Thank you very much !!

**Comment by andrewprzh** [comment]
@sandaruwanrat 

Seems like a bug in gffutils, so I now [fixed](https://github.com/ablab/IsoQuant/commit/0fed82cf158d7c1f110637c8150d021be0dac018) it just by ignoring problematic exons. The fix will be out in the next release.

Best
Andrey

**Comment by sandaruwanrat** [comment]
Hi @andrewprzh 

Now I am getting following error, Could you please check on this

```
2023-05-04 14:34:25,427 - INFO - Collecting read alignments
2023-05-04 14:34:29,551 - INFO - Processing chromosome AT2TE02465_Chr2_566757_582571
2023-05-04 14:34:29,553 - INFO - Processing chromosome AT5G20320_Chr5_6859212_6869266
2023-05-04 14:34:29,553 - INFO - Processing chromosome AT5G27610_Chr5_9764001_9770100
2023-05-04 14:34:33,547 - INFO - Processing chromosome AT5TE20395_Chr5_5629978_5635310
2023-05-04 14:34:33,546 - INFO - Processing chromosome AT5G43740_Chr5_17564601_17568900
2023-05-04 14:34:33,547 - INFO - Processing chromosome AT5G52070_Chr5_21160606_21166138
2023-05-04 14:34:33,548 - INFO - Processing chromosome AT1G05460_Chr1_1600863_1605200
2023-05-04 14:34:33,549 - INFO - Processing chromosome RUBY
2023-05-04 14:34:33,549 - INFO - Processing chromosome AT2G32940_Chr2_13971801_13977700
2023-05-04 14:34:33,551 - INFO - Processing chromosome AT5G43730_Chr5_17560063_17564500
2023-05-04 14:34:33,551 - INFO - Processing chromosome Chr4Tes_Chr4_4807323_4824162
2023-05-04 14:34:33,551 - INFO - Processing chromosome AT2G27040_Chr2_11536401_11542500
2023-05-04 14:34:33,551 - INFO - Processing chromosome AT1G48410_Chr1_17885633_17892800
2023-05-04 14:34:33,551 - INFO - Processing chromosome AT3G49500_Chr3_18348801_18353800
2023-05-04 14:34:33,551 - INFO - Processing chromosome AT2G40030_Chr2_16714294_16723733
2023-05-04 14:34:33,551 - INFO - Processing chromosome AT3TE64435_Chr3_15919028_15924078
2023-05-04 14:34:33,873 - INFO - Finished processing chromosome AT3TE64435_Chr3_15919028_15924078
2023-05-04 14:34:33,897 - INFO - Processing chromosome AT2G45660_Chr2_18807401_18811300
2023-05-04 14:34:34,047 - INFO - Finished processing chromosome Chr4Tes_Chr4_4807323_4824162
2023-05-04 14:34:34,075 - INFO - Processing chromosome AT5G38850_Chr5_15555078_15558900
2023-05-04 14:34:35,822 - INFO - Finished processing chromosome AT2TE02465_Chr2_566757_582571
2023-05-04 14:34:35,896 - INFO - Processing chromosome AT1G17370_Chr1_5951401_5955200
2023-05-04 14:34:40,546 - INFO - Finished processing chromosome AT5TE20395_Chr5_5629978_5635310
2023-05-04 14:34:40,597 - INFO - Processing chromosome ATMu1_Chr4_5541888_5545534
2023-05-04 14:34:41,140 - INFO - Finished processing chromosome ATMu1_Chr4_5541888_5545534
2023-05-04 14:34:41,176 - INFO - Processing chromosome AT1G63080_Chr1_23387401_23390900
2023-05-04 14:34:43,391 - INFO - Finished processing chromosome AT2G32940_Chr2_13971801_13977700
2023-05-04 14:34:43,524 - INFO - Processing chromosome AT3G11945_Chr3_3779639_3783054
2023-05-04 14:34:48,102 - INFO - Finished processing chromosome AT2G40030_Chr2_16714294_16723733
2023-05-04 14:34:48,315 - INFO - Processing chromosome AT1G08200_Chr1_2573701_2576983
2023-05-04 14:34:52,402 - INFO - Finished processing chromosome AT1G05460_Chr1_1600863_1605200
2023-05-04 14:34:52,652 - INFO - Processing chromosome AT5G23570_Chr5_7942908_7946150
2023-05-04 14:34:58,126 - INFO - Finished processing chromosome AT5G27610_Chr5_9764001_9770100
2023-05-04 14:34:58,436 - INFO - Processing chromosome AT5G03800_Chr5_1010766_1013678
2023-05-04 14:35:08,013 - INFO - Finished processing chromosome AT5G03800_Chr5_1010766_1013678
2023-05-04 14:35:08,140 - INFO - Processing chromosome AT1G63130_Chr1_23412401_23415300
2023-05-04 14:35:13,388 - INFO - Finished processing chromosome AT3G49500_Chr3_18348801_18353800
2023-05-04 14:35:13,973 - INFO - Processing chromosome AT2G20610_Chr2_8877701_8880600
2023-05-04 14:35:20,475 - INFO - Finished processing chromosome AT1G63080_Chr1_23387401_23390900
2023-05-04 14:35:20,987 - INFO - Processing chromosome AT2G39870_Chr2_16643201_16646000
2023-05-04 14:35:36,408 - INFO - Finished processing chromosome AT5G23570_Chr5_7942908_7946150
2023-05-04 14:35:36,791 - INFO - Processing chromosome AT3G13960_Chr3_4608076_4610599
2023-05-04 14:35:37,927 - INFO - Finished processing chromosome AT3G13960_Chr3_4608076_4610599
2023-05-04 14:35:37,958 - INFO - Processing chromosome AT1G63150_Chr1_23419196_23421679
2023-05-04 14:35:57,762 - INFO - Finished processing chromosome AT2G27040_Chr2_11536401_11542500
2023-05-04 14:35:58,483 - INFO - Processing chromosome AT1G62910_Chr1_23298857_23301058
2023-05-04 14:36:04,979 - INFO - Finished processing chromosome AT2G39870_Chr2_16643201_16646000
2023-05-04 14:36:05,390 - INFO - Processing chromosome AT1G66470_Chr1_24795014_24797188
2023-05-04 14:36:05,394 - INFO - Finished processing chromosome AT1G66470_Chr1_24795014_24797188
2023-05-04 14:36:05,413 - INFO - Processing chromosome AT1G62930_Chr1_23306534_23308686
2023-05-04 14:36:07,413 - INFO - Finished processing chromosome AT5G20320_Chr5_6859212_6869266
2023-05-04 14:36:08,245 - INFO - Processing chromosome AT5G59950_Chr5_24139739_24141867
2023-05-04 14:36:34,553 - INFO - Finished processing chromosome AT5G38850_Chr5_15555078_15558900
2023-05-04 14:36:35,502 - INFO - Processing chromosome AT1G62920_Chr1_23304313_23306374
2023-05-04 14:36:38,736 - INFO - Finished processing chromosome AT1G63150_Chr1_23419196_23421679
2023-05-04 14:36:39,399 - INFO - Processing chromosome AT1G06000_Chr1_1820108_1822094
2023-05-04 14:36:46,968 - INFO - Finished processing chromosome AT5G43730_Chr5_17560063_17564500
2023-05-04 14:36:47,905 - INFO - Processing chromosome AT1G06570_Chr1_2011885_2013745
2023-05-04 14:36:55,176 - INFO - Finished processing chromosome AT1G63130_Chr1_23412401_23415300
2023-05-04 14:36:55,932 - INFO - Processing chromosome AT1G63070_Chr1_23385324_23387167
2023-05-04 14:37:06,486 - INFO - Finished processing chromosome AT1G62910_Chr1_23298857_23301058
2023-05-04 14:37:07,346 - INFO - Processing chromosome GUS
2023-05-04 14:37:11,513 - INFO - Finished processing chromosome AT1G63070_Chr1_23385324_23387167
2023-05-04 14:37:11,704 - INFO - Processing chromosome AT4TE84225_Chr4_17449381_17451147
2023-05-04 14:37:11,937 - INFO - Finished processing chromosome AT4TE84225_Chr4_17449381_17451147
2023-05-04 14:37:11,961 - INFO - Processing chromosome AT2TE16940_Chr2_4005636_4007377
2023-05-04 14:37:24,085 - INFO - Finished processing chromosome AT1G06000_Chr1_1820108_1822094
2023-05-04 14:37:24,467 - INFO - Processing chromosome AT3G02550_Chr3_536500_538198
2023-05-04 14:37:25,459 - INFO - Finished processing chromosome AT1G62930_Chr1_23306534_23308686
2023-05-04 14:37:25,614 - INFO - Finished processing chromosome AT5G43740_Chr5_17564601_17568900
2023-05-04 14:37:26,094 - INFO - Processing chromosome AT3G12210_Chr3_3894678_3896066
2023-05-04 14:37:28,073 - INFO - Finished processing chromosome AT5G52070_Chr5_21160606_21166138
2023-05-04 14:37:28,287 - INFO - Processing chromosome AT5TE85500_Chr5_23774322_23775709
2023-05-04 14:37:30,562 - INFO - Finished processing chromosome AT5TE85500_Chr5_23774322_23775709
2023-05-04 14:37:30,918 - INFO - Processing chromosome AT3G17185_Chr3_5861301_5862600
2023-05-04 14:37:31,163 - INFO - Processing chromosome AT4TE16650_AT4TE16655_Chr4_3768073_3769181
2023-05-04 14:37:31,267 - INFO - Finished processing chromosome AT4TE16650_AT4TE16655_Chr4_3768073_3769181
2023-05-04 14:37:31,286 - INFO - Processing chromosome AT2TE47025_Chr2_10931247_10932314
2023-05-04 14:37:31,308 - INFO - Finished processing chromosome AT2TE47025_Chr2_10931247_10932314
2023-05-04 14:37:31,325 - INFO - Processing chromosome eGFP
2023-05-04 14:38:09,098 - WARNING - Gene RUBY has no exons / transcripts, check your input annotation
2023-05-04 14:38:09,163 - INFO - Processing chromosome AT3TE63860_Chr3_15794400_15794808
2023-05-04 14:38:09,241 - INFO - Finished processing chromosome AT3TE63860_Chr3_15794400_15794808
2023-05-04 14:38:28,707 - INFO - Finished processing chromosome AT3G12210_Chr3_3894678_3896066
2023-05-04 14:38:31,550 - INFO - Finished processing chromosome AT3G02550_Chr3_536500_538198
2023-05-04 14:38:58,464 - INFO - Finished processing chromosome AT1G62920_Chr1_23304313_23306374
2023-05-04 14:39:59,003 - INFO - Finished processing chromosome AT5G59950_Chr5_24139739_24141867
2023-05-04 14:40:45,040 - INFO - Finished processing chromosome eGFP
2023-05-04 14:43:12,795 - INFO - Finished processing chromosome AT1G17370_Chr1_5951401_5955200
2023-05-04 14:43:21,590 - INFO - Finished processing chromosome AT2G20610_Chr2_8877701_8880600
2023-05-04 14:43:27,393 - INFO - Finished processing chromosome AT3G11945_Chr3_3779639_3783054
2023-05-04 14:43:46,638 - INFO - Finished processing chromosome AT1G48410_Chr1_17885633_17892800
2023-05-04 14:46:16,265 - INFO - Finished processing chromosome AT1G06570_Chr1_2011885_2013745
2023-05-04 14:47:17,924 - INFO - Finished processing chromosome AT2TE16940_Chr2_4005636_4007377
2023-05-04 14:55:04,458 - INFO - Finished processing chromosome GUS
2023-05-04 14:59:17,248 - INFO - Finished processing chromosome AT3G17185_Chr3_5861301_5862600
2023-05-04 15:01:06,743 - INFO - Finished processing chromosome AT2G45660_Chr2_18807401_18811300
2023-05-04 15:01:29,596 - INFO - Finished processing chromosome AT1G08200_Chr1_2573701_2576983
2023-05-04 15:01:47,614 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesconcurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/dataset_processor.py", line 112, in collect_reads_in_parallel
    for gene_info, assignment_storage in alignment_collector.process():
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/alignment_processor.py", line 248, in process
    for res in self.forward_alignments(alignment_storage):
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/alignment_processor.py", line 257, in forward_alignments
    yield self.process_alignments_in_region(current_region, alignment_storage.get_alignments())
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/alignment_processor.py", line 269, in process_alignments_in_region
    assignment_storage = self.process_genic(alignment_storage, gene_info)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/alignment_processor.py", line 345, in process_genic
    read_assignment = assigner.assign_to_isoform(read_id, alignment_info.combined_profile)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/long_read_assigner.py", line 417, in assign_to_isoform
    gene_region = (self.gene_info.split_exon_profiles.features[0][0],
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tratnayake/miniconda3/envs/isoquant/bin/isoquant.py", line 687, in <module>
    main(sys.argv[1:])
  File "/home/tratnayake/miniconda3/envs/isoquant/bin/isoquant.py", line 681, in main
    run_pipeline(args)
  File "/home/tratnayake/miniconda3/envs/isoquant/bin/isoquant.py", line 637, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/dataset_processor.py", line 364, in process_all_samples
    self.process_sample(sample)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/dataset_processor.py", line 387, in process_sample
    self.collect_reads(sample)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/dataset_processor.py", line 444, in collect_reads
    for storage, read_groups in results:
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
IndexError: list index out of range


```


Thank you very much


Best Regards
Sandaruwan

**Comment by andrewprzh** [comment]
@sandaruwanrat 

Seems like the same problem that comes from unusual GTF features and gffutils. Is if possible to send the reference genome and the BAM file (can be a subset of reads from this region)?

Best
Andrey

**Comment by andrewprzh** [comment]
@sandaruwanrat 

I have a *presumable* [fix](https://github.com/ablab/IsoQuant/commit/133f9b7053626badbe1e71e73af29c8241ba4ae5), but it's hard to tell for sure whether it fixes all the problems that can arise with this annotation. You can try it yourself or send me the data.

Best
Andrey

**Comment by sandaruwanrat** [comment]
Hi @andrewprzh 

Thank you very much for testing. I really appreciate it.

Best Regards
Sandaruwan

**Comment by sandaruwanrat** [comment]
Hi @andrewprzh 

When I run with  `--complete_genedb` it runs whole analysis. However, when I try to run it without the flag, I am getting following error. 

```
Traceback (most recent call last):
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/dataset_processor.py", line 111, in collect_reads_in_parallel
    for gene_info, assignment_storage in alignment_collector.process():
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/alignment_processor.py", line 242, in process
    for res in self.forward_alignments(alignment_storage):
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/alignment_processor.py", line 257, in forward_alignments
    yield self.process_alignments_in_region(current_region, alignment_storage.get_alignments())
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/alignment_processor.py", line 265, in process_alignments_in_region
    gene_info = self.get_gene_info_for_region(current_region)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/alignment_processor.py", line 445, in get_gene_info_for_region
    gene_info = GeneInfo(gene_list, self.genedb, self.params.delta)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/gene_info.py", line 155, in __init__
    self.set_junction_profiles(self.all_isoforms_introns, self.all_isoforms_exons)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/gene_info.py", line 581, in set_junction_profiles
    transcript_region = self.transcript_region(t.id)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/gene_info.py", line 598, in transcript_region
    return (self.transcript_start(transcript_id), self.transcript_end(transcript_id))
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/gene_info.py", line 592, in transcript_start
    return self.all_isoforms_exons[transcript_id][0][0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tratnayake/miniconda3/envs/isoquant/bin/isoquant.py", line 695, in <module>
    main(sys.argv[1:])
  File "/home/tratnayake/miniconda3/envs/isoquant/bin/isoquant.py", line 689, in main
    run_pipeline(args)
  File "/home/tratnayake/miniconda3/envs/isoquant/bin/isoquant.py", line 642, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/dataset_processor.py", line 368, in process_all_samples
    self.process_sample(sample)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/dataset_processor.py", line 392, in process_sample
    self.collect_reads(sample)
  File "/shares/kslotkin_share/private/tratnayake/miniconda3/envs/isoquant/share/isoquant-3.2.0-0/src/dataset_processor.py", line 449, in collect_reads
    for storage, read_groups in results:
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/tratnayake/miniconda3/envs/isoquant/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
IndexError: list index out of range
```


Thank you very much.

Best Regards
Sandaruwan

**Comment by andrewprzh** [comment]
Dear @sandaruwanrat 

Thanks for reporting, should have tested this scenario too. 
Seems like gffutils goes crazy with this annotation, which contains non-standard feature types.

I made a hot [fix](https://github.com/ablab/IsoQuant/commit/a5f69e14c8325ff03f4f06bb8ba68877c62572fc) in master, works on your data, but probably needs a bit more testing. You can try it out now, though.

Best
Andrey

**Comment by sandaruwanrat** [comment]
Hi @andrewprzh 

Thank you very much.


Best Regards
Sandaruwan
