### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by enzeas** [ablab/IsoQuant#90]
version used IsoQuant 3.2.0

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/datf/enzedeng/mambaforge/envs/sc/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/datf/enzedeng/mambaforge/envs/sc/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/datf/enzedeng/mambaforge/envs/sc/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/dataset_processor.py", line 112, in collect_reads_in_parallel
    for gene_info, assignment_storage in alignment_collector.process():
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/alignment_processor.py", line 242, in process
    for res in self.forward_alignments(alignment_storage):
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/alignment_processor.py", line 261, in forward_alignments
    yield self.process_alignments_in_region(new_region, alignments)
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/alignment_processor.py", line 265, in process_alignments_in_region
    gene_info = self.get_gene_info_for_region(current_region)
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/alignment_processor.py", line 445, in get_gene_info_for_region
    gene_info = GeneInfo(gene_list, self.genedb, self.params.delta)
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/gene_info.py", line 161, in __init__
    self.set_gene_attributes()
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/gene_info.py", line 429, in set_gene_attributes
    self.gene_attributes[gene_db.id] += '%s "%s"; ' % (attr, gene_db.attributes[attr][0])
IndexError: list index out of range
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/datd/enzedeng/software/GitHub/IsoQuant/isoquant.py", line 687, in <module>
    main(sys.argv[1:])
  File "/datd/enzedeng/software/GitHub/IsoQuant/isoquant.py", line 681, in main
    run_pipeline(args)
  File "/datd/enzedeng/software/GitHub/IsoQuant/isoquant.py", line 637, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/dataset_processor.py", line 364, in process_all_samples
    self.process_sample(sample)
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/dataset_processor.py", line 387, in process_sample
    self.collect_reads(sample)
  File "/datd/enzedeng/software/GitHub/IsoQuant/src/dataset_processor.py", line 444, in collect_reads
    for storage, read_groups in results:
  File "/datf/enzedeng/mambaforge/envs/sc/lib/python3.10/concurrent/futures/process.py", line 570, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/datf/enzedeng/mambaforge/envs/sc/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/datf/enzedeng/mambaforge/envs/sc/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/datf/enzedeng/mambaforge/envs/sc/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/datf/enzedeng/mambaforge/envs/sc/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
IndexError: list index out of range

**Comment by andrewprzh** [comment]
Dear @enzeas 

This looks weird, could you please send the GTF you used in the run?
I will add some additional check in the next release.

Best
Andrey

**Comment by andrewprzh** [comment]
Please check whether the error can be reproduced using IsoQuant 3.3.

Best
Andrey

**Comment by enzeas** [comment]
error is fixed by IsoQuant 3.3.
