### ISSUE TITLE
Error while converting gene annotation file to .db format step

### ISSUE THREAD

**Issue by Kyung-TaeLee** [ablab/IsoQuant#95]
Hi, I am currently trying to run isoquant to quantify isoform expression of Nanopore cDNA sequencing data from Drosophila larvae. I successfully installed isoquant version 3.3.0 through conda and ran the command as follows.

###
isoquant.py --reference /home/kyungtae/reference/fly/BDGP6.22/genome/Drosophila_melanogaster.BDGP6.22.manual.fasta --genedb /home/kyungtae/reference/fly/BDGP6.22/geneAnno/Drosophila_melanogaster.BDGP6.22.manual.gtf --bam /home/kyungtae/dataset/fly_waspInfest_lncRNA/nanopore/RNA_run/merged_fly_2020_10_18/rawData/pychopper_trim/120AEL_WT_blood/5.minimap2/lordec_minimap2/120AEL_WT_blood.merged.nanofilt.pychopper.lordec.sorted.bam --data_type nanopore -o /home/kyungtae/dataset/fly_waspInfest_lncRNA/nanopore/RNA_run/merged_fly_2020_10_18/rawData/pychopper_trim/120AEL_WT_blood/test/isoquant/ --clean_start -t 30 --complete_genedb
###

Running log is as follows : 

###
2023-06-23 17:41:00,210 - INFO - Running IsoQuant version 3.3.0
2023-06-23 17:41:00,210 - WARNING - Output folder already contains a previous run, some files may be overwritten. Use --resume to resume a failed run. Use --force to avoid this message. Press Ctrl+C to interrupt the run now.
2023-06-23 17:41:09,228 - INFO - Overwriting the previous run
2023-06-23 17:41:10,242 - WARNING - /home/kyungtae/dataset/fly_waspInfest_lncRNA/nanopore/RNA_run/merged_fly_2020_10_18/rawData/pychopper_trim/120AEL_WT_blood/test/isoquant/OUT folder already exists, some files may be overwritten
2023-06-23 17:41:10,242 - WARNING - /home/kyungtae/dataset/fly_waspInfest_lncRNA/nanopore/RNA_run/merged_fly_2020_10_18/rawData/pychopper_trim/120AEL_WT_blood/test/isoquant/OUT/aux folder already exists, some files may be overwritten
2023-06-23 17:41:10,244 - INFO - Novel unspliced transcripts will not be reported, set --report_novel_unspliced true to discover them
2023-06-23 17:41:10,245 - INFO -  === IsoQuant pipeline started === 
2023-06-23 17:41:10,246 - INFO - Converting gene annotation file to .db format (takes a while)...
2023-06-23 17:41:56,209 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesTraceback (most recent call last):
  File "/home/kyungtae/programs/yes/envs/isoquant/lib/python3.8/site-packages/gffutils/create.py", line 790, in _populate_from_lines
    self._insert(f, c)
  File "/home/kyungtae/programs/yes/envs/isoquant/lib/python3.8/site-packages/gffutils/create.py", line 566, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.IntegrityError: UNIQUE constraint failed: features.id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kyungtae/programs/yes/envs/isoquant/bin/isoquant.py", line 698, in <module>
    main(sys.argv[1:])
  File "/home/kyungtae/programs/yes/envs/isoquant/bin/isoquant.py", line 692, in main
    run_pipeline(args)
  File "/home/kyungtae/programs/yes/envs/isoquant/bin/isoquant.py", line 631, in run_pipeline
    args.genedb = convert_gtf_to_db(args)
  File "/lustre/export/home/kyungtae/programs/yes/envs/isoquant/share/isoquant-3.3.0-0/src/gtf2db.py", line 110, in convert_gtf_to_db
    gtf_filename, genedb_filename = convert_db(gtf_filename, genedb_filename, gtf2db, args)
  File "/lustre/export/home/kyungtae/programs/yes/envs/isoquant/share/isoquant-3.3.0-0/src/gtf2db.py", line 158, in convert_db
    convert_fn(gtf_filename, genedb_filename, args.complete_genedb)
  File "/lustre/export/home/kyungtae/programs/yes/envs/isoquant/share/isoquant-3.3.0-0/src/gtf2db.py", line 95, in gtf2db
    gffutils.create_db(gtf, db, force=True, keep_order=True, merge_strategy='error',
  File "/home/kyungtae/programs/yes/envs/isoquant/lib/python3.8/site-packages/gffutils/create.py", line 1401, in create_db
    c.create()
  File "/home/kyungtae/programs/yes/envs/isoquant/lib/python3.8/site-packages/gffutils/create.py", line 543, in create
    self._populate_from_lines(self.iterator)
  File "/home/kyungtae/programs/yes/envs/isoquant/lib/python3.8/site-packages/gffutils/create.py", line 792, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/home/kyungtae/programs/yes/envs/isoquant/lib/python3.8/site-packages/gffutils/create.py", line 257, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID FBgn0013687
###

Error seems bit weird because I check the gene ID "FBgn0013687" and it doesn't seem to be duplicated. I will attach the gene annotation file in here (it is BDGP6.22 gene annotation file). Thank you for developing such a nice tool and hope you can help me resolve this issue.

[Drosophila_melanogaster.BDGP6.22.manual.gtf.gz](https://github.com/ablab/IsoQuant/files/11846530/Drosophila_melanogaster.BDGP6.22.manual.gtf.gz)

**Comment by andrewprzh** [comment]
Dear @Kyung-TaeLee 

I think the problem is that gffutils does not like duplicated ids across all features. I guess it uses them as keys in the database.
The gene you referred to contains a transcript with the same id 
```
gene_id "FBgn0013687"; transcript_id "FBgn0013687";
```

Thus, the best way would be probably rename this transcripts to e.g. FBgn0013687.1.
If there are multiple cases like this, I think it worth writing a script that renames all the transcripts.

Sorry for inconvenience, all I can do is to add a check into IsoQuant at some point. 

Best
Andrey

**Comment by Kyung-TaeLee** [comment]
Thank you for the quick response! Now it's working perect and quantification of transcript abundance seem so accurate. Thank you for your help

Best
Kyung-Tae Lee

**Comment by CorentinAube** [comment]
Thank you for your answer.

I fixed my gtf but the problem is still going on.
I tested to run IsoQuant just with my human GTF but the problem is still there. So i think my human GTF is not good.

I also tested with only my viral GTF, and it's work until this error : 

2023-07-06 14:42:20,536 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesconcurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/mnt/d/Corentin/IsoQuant/src/dataset_processor.py", line 109, in collect_reads_in_parallel
    AlignmentCollector(chr_id, bam_file_pairs, args, gffutils_db, current_chr_record, read_grouper)
  File "/mnt/d/Corentin/IsoQuant/src/alignment_processor.py", line 227, in __init__
    self.bam_merger = BAMOnlineMerger(self.bam_pairs, self.chr_id, 0,
  File "/mnt/d/Corentin/IsoQuant/src/alignment_processor.py", line 41, in __init__
    self._set(chr_id, start, end)
  File "/mnt/d/Corentin/IsoQuant/src/alignment_processor.py", line 53, in _set
    self.current_elements.put_nowait(make_alignment_tuple(i, next(it)))
  File "pysam/libcalignmentfile.pyx", line 2107, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "isoquant.py", line 698, in <module>
    main(sys.argv[1:])
  File "isoquant.py", line 692, in main
    run_pipeline(args)
  File "isoquant.py", line 645, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/mnt/d/Corentin/IsoQuant/src/dataset_processor.py", line 368, in process_all_samples
    self.process_sample(sample)
  File "/mnt/d/Corentin/IsoQuant/src/dataset_processor.py", line 392, in process_sample
    self.collect_reads(sample)
  File "/mnt/d/Corentin/IsoQuant/src/dataset_processor.py", line 449, in collect_reads
    for storage, read_groups in results:
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
OSError: truncated file 

Thank you for your feed back!
Corentin

**Comment by NanoCoreUSA** [comment]
Just wanted to chime in since I ran into a similar error when using a new GFF3 file from GENCODE (Human v44). 

gffutils has an option in the 'create_db' command to create unique values. From the [README](https://daler.github.io/gffutils/autodocs/gffutils.create.create_db.html) - 

> Using merge_strategy="create_unique", then the first entry will use the original primary key, but the second entry will have a unique, autoincremented primary key assigned to it

I tried a few GFF3 'cleaner' tools to fix my error and eventually just changed database creation command in 'gtf2db.py' file from 'error' to 'create_unique'. Seems to work fine now, but wondering if there's any downstream affects you can think of where this might be a problem.
