### ISSUE TITLE
Error during processing of assigned reads

### ISSUE THREAD

**Issue by ddpinto** [ablab/IsoQuant#96]
During isoquant processing of a large dataset with 50 samples we encountered the following error during the processing of assigned reads. Any suggestions on how to resolve this error would be most appreciated.

```
2023-06-26 15:14:33,818 - CRITICAL - IsoQuant failed with the following error, please, submit this issue to https://github.com/ablab/IsoQuant/issuesconcurrent.futures.process._RemoteTraceback: 
Traceback (most recent call last):
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/share/isoquant-3.3.0-0/src/dataset_processor.py", line 228, in construct_models_in_parallel
    sqanti_t2t_printer.add_read_info(a)
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/share/isoquant-3.3.0-0/src/assignment_io.py", line 410, in add_read_info
    read_assignment.exon_count(), match.match_classification.name, gene_id, transcript_id,
UnboundLocalError: local variable 'match' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/bin/isoquant.py", line 698, in <module>
    main(sys.argv[1:])
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/bin/isoquant.py", line 692, in main
    run_pipeline(args)
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/bin/isoquant.py", line 645, in run_pipeline
    dataset_processor.process_all_samples(args.input_data)
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/share/isoquant-3.3.0-0/src/dataset_processor.py", line 368, in process_all_samples
    self.process_sample(sample)
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/share/isoquant-3.3.0-0/src/dataset_processor.py", line 406, in process_sample
    self.process_assigned_reads(sample, saves_file)
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/share/isoquant-3.3.0-0/src/dataset_processor.py", line 539, in process_assigned_reads
    for read_stat_counter, tsc in results:
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/sc/arion/work/snakemake/993494c51259d95d13572baf13d0cade_/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
UnboundLocalError: local variable 'match' referenced before assignment
```

**Comment by andrewprzh** [comment]
Dear @ddpinto 

Seems like a bug in SQANTI-like file output, thanks for the report. Immediate solution would be to remove `--sqanti_output` option.

[This commit](https://github.com/ablab/IsoQuant/commit/c98725d83f4fe2070a4fa01754b5f46f642966cc) presumably fixes it, it will be included in the next release.

Best
Andrey

**Comment by ddpinto** [comment]
Hi Andrey,
I sent it by email but posting it here as well. Your commit to fix the --sqanti_output works well, thanks.

Best
